Adj_case_e1
aneka
anekano/anekanO/anekanau/anekau
anekano/anekanO/anekanau/anekau
kai
kaiyano/kaiyanO/kaiyanau/kaiano/kaianO/kaianau
kaiyano/kaiyanO/kaiyanau/kaiano/kaianO/kaianau
kaI
kaiyano/kaiyanO/kaiyanau/kaiano/kaianO/kaianau/kaiyau/kaiau/kaiyo
kaiyano/kaiyanO/kaiyanau/kaiano/kaianO/kaianau/kaiyau/kaiau/kaiyo
bIsa
bIsoM/bisOM/bisau/bisiyoM/bisiyOM/bisiyau/bisiano/bisianO/bisianau/bisano/bisanO/bIsanau
bIsoM/bisOM/bisau/bisiyoM/bisiyOM/bisiyau/bisiano/bisianO/bisianau/bisano/bisanO/bIsanau
ikAnabe
ikAnabevano/ikAnabevanO/ikAnabevanau/ikAnabeno/ikAnabenO/ikAnabenau
ikAnabevano/ikAnabevanO/ikAnabevanau/ikAnabeno/ikAnabenO/ikAnabenau
xonoM
xonau/xunno/xunnau/xUnau/xUnno/xunnO
xonau/xunno/xunnau/xUnau/xUnno/xunnO
sEkadZoM
sEkadZoM/sEkadZOM/sEkadZau/sEkadZano/sEkadZanO/sEkadZanau
sEkadZoM/sEkadZOM/sEkadZau/sEkadZano/sEkadZanO/sEkadZanau
sO
savano/savanO/savanau/sauvano/sauvanO/sauvanau/sauvo/sauvO/sauvau
savano/savanO/savanau/sauvano/sauvanO/sauvanau/sauvo/sauvO/sauvau
