Adj_All_e
amIra
amIrai/amIre/amIrE
kariyA
kariyai/kariai/kariye
gora
gorai/gorE/gore
nIlA
nIlai/nIlE/nIle
pIyara
pIyarai/pIyare/pIarai/pIare
asamAnI
asamaniyai/asamaniai/asamaniye/asamanie
aura
aurau/auri/auru
cAlU
caluvai/caluai/cAlue/cAluvai/cAluai/calue/cAluye/cAluve/cAlUye/cAlUve
abuxXi
abuxXiyai/abuxXiai/abuxXiye/abuxXie
asawru
asawruai/asawruyai/asawruye/asawrue
aBE
aBEe/aBEye
jIro
jIrovai/jIrove/jIroe/jIroiye/jIroie/jIroai
javAz
javez/javeM
BaxaIz
Baxaizyez/BaxaiMyeM/Baxaiez/BaxaieM/Baxaizez/BaxaiMeM/BaxaizyeM/BaxaiMyez
aPajUM
aPajuMyeM/aPajuzyez/aPajuMyez/aPajuzyeM/aPajuMeM/aPajuzez/aPajuMez/aPajuzeM
ekasOM
ekasIMeM/ekasOzez/ekasOMez/ekasOzeM

