Adj_case_e
aneka
anekana/anekai
anekana/anekai
kai
kaiyana/kaiana
kaiyana/kaiana
kaI
kaiyana/kaiana/kaiye/kaie
kaiyana/kaiana/kaiye/kaie
bIsa
bIsana/bisana/bIsoM/bisiyana/bisiana/bisOM/bisiyoM
bIsana/bisana/bIsoM/bisiyana/bisiana/bisOM/bisiyoM
ikAnabe
ikAnabevana
ikAnabevana
xonoM
xonoM/xonau/xunno/xunnau/xUnau/xUnno/xunnO
xonoM/xonau/xunno/xunnau/xUnau/xUnno/xunnO
saba
sabE/saBE/sabahi/sabahI/saBahi/saBahI/saBe/sabe
sabE/saBE/sabahi/sabahI/saBahi/saBahI/saBe/sabe
sEkadZoM
sEkadZoM/sEkadZana
sEkadZoM/sEkadZana
sO
savana/sauvana
savana/sauvana
