Advrb_e
aba
abbai/abai/aBI/abahi/abahI
kala
kalai/kAlhai/kalE/kAlhE
Aja
Ajai/AjE/Ajahi/Ajuve
parasoM
parasavaiz/parasaveM/parasavahi/parasave/parasoMveM/parasoveM/parasoMyeM/parasoMeM/parasozvez/parasovez/parasozyeM/parasoMez
bihAna
bihAnai/bihAne/bihAnE/bihanai
sabere
sabarahi/sabarahI/saberahi/saberahI/saberai
subaha
subahai/subahiyai/subahe
XIre
XirahI/Xirahi/XirehI/XIrehi/XirahIM/XirahiM
hamesA
hamesahi/hamesahI/hamesai
nIce
nIcahi/nIcahI/nIcahai/nicehI/nicehi/nIcahE
aso
asavai/asave/asavahi/asave/asove/asoye/asoe
begahUz
begahuzveM/begahuMveM/begahuzvez/begahuMvez/begahuzyeM/begahuMyeM/begahuzyez/begahuMyez
anaxeKe
anaxeKalai/anaxeKale
ahewu
ahewue/ahewuve/ahewuye
beAbarU
beAbarue/beAbaruve/beAbaruye
awi
awiye/awie/awiyai/awiai
kaBI
kaBiye/kaBie/kaBiyai
abahIz
abahizye/abahiMye/abahize/abahiMe/abahiMyai/abahizyai
jahAz
jahez/jaheM/jahEz/jahEM
