Future
KA
KAba/KAiba/KAyeba
KaibA/KAbA/KaibaV
KaihaMi/KAyeba/Kaihazi/Kaihana/KAiba
KAi
KAba/KAiba/KAyeba
KaibaV/KAbA/KaibA
KaihaMi/KAyeba/Kaihazi/Kaihana/KAiba
Kaihana/KaihaMi/Kaihazi
KAba/KAiba/KAyeba
Kaibu/KAbu/KaibU/KAbU/KaibI
KaihaMi/KAyeba/Kaihazi/Kaihana/KAiba
KAi
KAba/KAiba/KAyeba
Kaibu/KAbu/KaibU/KAbU/KaibI
KaihaMi/KAyeba/Kaihazi/Kaihana/KAiba
Kaihana/KaihaMi/Kaihazi
-
-
KaihaMi/KAyeba/Kaihazi/Kaihana/KAiba
-
-
-
KaihaMi/KAyeba/Kaihazi/KAiba
-
kara
karaba/kareba
karabaV/karabA
karihaMi/kareba/karihazi/karihana/karabA
kari/karI
karaba/kareba
karabaV/karabA
karihaMi/kareba/karihazi/karihana/karabA/karaba
karihana/karihaMi/karihazi
karaba/kareba/karema
karabU
karihaMi/kareba/karihazi/karihana/karaba
kari
karihaMi/kareba/karihazi/karaba
karabU/karabI
karihaMi/kareba/karihazi/karihana/karaba
karihaMi/kareba/karihazi/karihana
-
-
karihaMi/kareba/karihazi/karaba
-
-
-
karihaMi/kareba/karihazi/karaba
-
le
leba/lebai/lebE
lebaV/lebe/lebA
leihaMi/leihazi/lebai/lebE/leba/lihana
lei/lehi/lehI/lihi/liheM
leba/lebai/lebE
lebaV/lebA
leihaMi/leihazi/lebai/lebE/leba/lihana
leihaMna/leihazna/lihazi/lihaMi/lihana
leba/lebai/lebE
lebu/lebU
leihaMi/leihazi/lebai/lebE/leba/lihana
lei/lehi/lehI/lihi/liheM
leba/lebai/lebE
lebu/lebU/lebI
leihaMi/leihazi/lebai/lebE/leba/lihana
leihaMna/leihazna/lihazi/lihaMi/lihana
-
-
leba/leihaMna/leihazna/lihazi/lihaMi
-
-
-
leihaMi/leihazi/lebai/lebE/leba
-
ho
hoKaba/hoiba/hoba/hobE
hoKabA/hoibaV/hobA/hoibA/hoKabaV
hoKabA/hoiba/hobA/hoibA/hoihazi/hoihaMi/hoKaba/hoihana/hoKihana
hoI
hoKaba/hoiba/hoyeba
hoKabA/hoibaV/hobA/hoibA/hoKabaV
hoKabA/hoiba/hobA/hoibA/hoihazi/hoihaMi/hoKaba/hoihana/hoKihana
hoihazi/hoihaMi/hoihana
hoKaba/hoiba/hoba/hobE
hoibu/hobu/hoibU/hobU/hoKabu/hoKabU/hobI
hoihazi/hoihaMi/hoKaba/hoihana/hoKihana/hoKema
hoi/hoKi
hoKaba/hoiba/hoyeba
hoibu/hobu/hoibU/hobU/hoKabu/hoKabU/hoKabi
hoihazi/hoihaMi/hoKaba
hoihazi/hoihaMi/hoihana
-
-
hoihaMi/hoyeba/hoihazi
-
-
-
hoihazi/hoihaMi/hoKaba
-
pI
piaba/pIaba/piyaba/pIyaba/piyeba
piabaV/pIabaV/piyabaV/pIyabaV/piabA/pIabA/piyabA/pIyabA
piihaMi/piyeba/piihazi/pIihaMi/pIyeba/pIihazi/pihana/piema
pihi/pihI/pIhi/pIhI
piaba/pIaba/piyaba/pIyaba/piyeba
piabaV/pIabaV/piyabaV/pIyabaV/piabA/pIabA/piyabA/pIyabA
piihaMi/piyeba/piihazi/pIihaMi/pIyeba/pIihazi/pihana
piihana/piihaMi/piihazi/pIihana/pIihaMi/pIihazi/pihana
piaba/pIaba/piyaba/pIyaba/piyeba
piyabU/piabU/pibU/pIyabU/pIabU/pIbU/piyabu/piabu/pibu/pIyabu/pIabu/pIbu/piyabi
piihazi/pIihaMi/pIyeba/pIihazi/pihana
pihi/pihI/pIhi/pIhI
piaba/pIaba/piyaba/pIyaba/piyeba
piyabU/piabU/pibU/pIyabU/pIabU/pIbU/piyabu/piabu/pibu/pIyabu/pIabu/pIbu/piyabi
piihazi/pIihaMi/pIyeba/pIihazi/pIyaba/pIema
piihana/piihaMi/piihazi/pIihana/pIihaMi/pIihazi
-
-
piihaMi/piyeba/piihazi/pIihaMi/pIyeba/pIihazi
-
-
-
piihaMi/piyeba/piihazi/pIihaMi/pIyeba/pIihazi
-
CU
CUaba/Cuaba/CUyaba/Cuyaba/CUyeba
CUabaV/CuabaV/CUyabaV/CuyabaV/CUabA/CuabA/CUyabA/CuyabA/Cuabai/Cuabe
CUihaMi/CUyeba/CUihazi/CuihaMi/Cuyeba/Cuihazi/Cuaba/Cuema
CUhi/CUhI/Cuhi/CuhI/Cui/CUi
CUaba/Cuaba/CUyaba/Cuyaba/CUyeba/Cuema
CUabaV/CuabaV/CUyabaV/CuyabaV/CUabA/CuabA/CUyabA/CuyabA
CUihaMi/CUyeba/CUihazi/CuihaMi/Cuyeba/Cuihazi
CUihana/CUihaMi/CUihazi/Cuihana/CuihaMi/Cuihazi
CUaba/Cuaba/CUyaba/Cuyaba/CUyeba
CUyabU/CUabU/CUbU/CuyabU/CuabU/CubU/CUyabu/CUabu/CUbu/Cuyabu/Cuabu/Cubu/CuabI/CUabI/CUabe
CUihazi/CuihaMi/Cuyeba/Cuihazi
CUhi/CUhI/Cuhi/CuhI/CUi/Cui
CUaba/Cuaba/CUyaba/Cuyaba/CUyeba
CUyabU/CUabU/CUbU/CuyabU/CuabU/CubU/CUyabu/CUabu/CUbu/Cuyabu/Cuabu/Cubu/CuabI/CUabI
CUihazi/CuihaMi/Cuyeba/Cuihazi
CUihana/CUihaMi/CUihazi/Cuihana/CuihaMi/Cuihazi
-
-
CUihaMi/CUyeba/CUihazi/CuihaMi/Cuyeba/Cuihazi
-
-
-
CUihaMi/CUyeba/CUihazi/CuihaMi/Cuyeba/Cuihazi
-
uTa
uTaba/uTeba
uTabaV/uTabA/uTabe/uTabai
uTihaMi/uTihazi/uTeba/uTabA/uTaba/uTema
uTi/uTI
uTaba/uTeba
uTabaV/uTabA
uTihaMi/uTihazi/uTihana
uTihana/uTihaMi/uTihazi
uTaba/uTeba
uTabu/uTabU/uTabI
uTihaMi/uTihazi/uTeba/uTihana
uTi/uTI/uTihana
uTihaMi/uTihazi/uTeba
uTabu/uTabU/uTabi
uTihaMi/uTihazi/uTeba/uTihana
uTihana/uTihaMi/uTihazi
-
-
uTihaMi/uTihazi/uTeba
-
-
-
uTihaMi/uTihazi/uTeba
-
so
soaba/soyaba/soyeba/soiba
soabaV/soyabA/soibA
soaba/soyaba/soyeba/soiba
soi
soaba/soyaba/soyeba/soiba
soabaV/soyabA/soibA
soaba/soyaba/soyeba/soiba
soihana/soihaMi/soihazi
soaba/soyaba/soyeba/soiba
soabu/soyabu/soibu/soabU/soyabU/soibU
soaba/soyaba/soyeba/soiba
soi
soaba/soyaba/soyeba/soiba
soabu/soyabu/soibu/soabU/soyabU/soibU
soihazi/soihaMi/soyeba
soihana/soihaMi/soihazi
-
-
soihaMi/soyeba/soihazi/soihazi
-
-
-
soihaMi/soyeba/soihazi/soihazi
-
se
seaba/seyaba/seyeba/seiba
seabaV/seyabA/seibA/seibe/seibai
seaba/seyaba/seyeba/seiba/seihana
sei
seaba/seyaba/seyeba/seiba
seabaV/seyabA/seibA/seibe/seibai
seaba/seyaba/seyeba/seiba/seihana
seihana/seihaMi/seihazi
seaba/seyaba/seyeba/seiba
seabu/seyabu/seibu/seabU/seyabU/seibU/seibi
seaba/seyaba/seyeba/seiba/seihana
sei
seaba/seyaba/seyeba/seiba
seabu/seyabu/seibu/seabU/seyabU/seibU/seibi
seihazi/seihaMi/seyeba/seihana
seihana/seihaMi/seihazi
-
-
seihaMi/seyeba/seihazi/seihazi
-
-
-
seihaMi/seyeba/seihazi/seihazi
-
