Future_e1
KA
Kaibo/Kayabo/Kabau/KAbau
kara
karabo/karabau
le
lebo/lehabo/leyabo/lehabau
ho
hobo/hoibo/hobau
pI
pibo/piabo/piyabo/pIbo/pIabo/pIyabo/pIbau/pibau
CU
CUbo/CUabo/CUyabo/Cubo/Cuabo/Cuyabo/CUvabo/Cuvabo/Cubau/CUbau
uTa
uTabo/uTabau
so
soabo/soubo/soyabo/sobau
se
seabo/seyabo/seubo/sebau
