Gerund_ba_e
KA
Kaibai/KAbE/Kavabai/KavabE
kara
karabai/karabE
uTa
uTabai/uTabE
ho
hoibai/hobai/hoibE/hovabai/hovabE
pI
piabai/piyabai/pIyabai/pIabai/piabE/piyabE/pIabE/pIyabE/pivabai/pivabE/pIvabai/pIvabE
CU
Cuabai/Cuvabai/CUabai/CUvabai/CUvabE/CUabE/CuvabE/CuabE
so
soabai/sovabai/soibai/soabE/soyabE
se
seabai/sevabai/seibai/seyabE/seyabai/seabE/sevabE/seibE
le
lebai/lebE/levabai/levabE
xe
xebai/xebE/xevabai/xevabE
