Gerund_ba_e1
KA
KAbau/KailoV/Kavabau/KavabO
kara
karabau/kailoV/kayaloV/karabO
uTa
uTabau/uTaloV
ho
hobau/hoiloV/hoibau/hovabau/hovabO
pI
piyabau/pIabau/pIyabau/pialoV/piyaloV/pIaloV/pIyaloV/pivabau/pIvabau/pivabO/pIvabO
CU
Cuabau/Cubau/Cuvabau/CualoV/CuvaloV/CuyaloV/CUabau/CUbau/CUvabau/CUaloV/CUvaloV/CUyaloV/Cuvabau/CUvabau/CuvabO/CUvabO
so
soibau/soyabau/soyalau/soalau/soyaloV/soaloV/sovabau/sovabO
se
seibau/seyabau/seyalau/sealau/seyaloV/sealoV/sevabau/sevabO
le
lebau/lebo/levabau/levabO
xe
xebau/xebo/xevabau/xevabO
