Infinitive_yeke
KA
KAyeke
KAyeke
KAyeke
KAyeke
kara
kareke/karaike
kareke/karaike
kareke/karaike
kareke/karaike
le
leveke/levaike
leveke/levaike
leveke/levaike
leveke/levaike
ho
hoveke/hoyeke/hovaike
hoveke/hoyeke/hovaike
hoveke/hoyeke/hovaike
hoveke/hoyeke/hovaike
pI
piyaike/piyeke/pIyaike/pIyeke
piyaike/piyeke/pIyaike/pIyeke
piyaike/piyeke/pIyaike/pIyeke
piyaike/piyeke/pIyaike/pIyeke
CU
CUveke/CUyeke/CUvaike/Cuveke/Cuyeke/Cuvaike
CUveke/CUyeke/CUvaike/Cuveke/Cuyeke/Cuvaike
CUveke/CUyeke/CUvaike/Cuveke/Cuyeke/Cuvaike
CUveke/CUyeke/CUvaike/Cuveke/Cuyeke/Cuvaike
uTa
uTeke/uTaike
uTeke/uTaike
uTeke/uTaike
uTeke/uTaike
so
soveke/soyeke/sovaike
soveke/soyeke/sovaike
soveke/soyeke/sovaike
soveke/soyeke/sovaike
se
seveke/sevaike
seveke/sevaike
seveke/sevaike
seveke/sevaike
