kara_e1
KA
Kaiyoke/Kaihoke/KaihukeV/KaihUkeV
kara
karayoke/kariyoke/karahoke/karihoke
le
leiyoke/leioke/lehoke/levoke/lehuvoke/lehukeV/lehUkeV
ho
hoiyoke/hoioke/hovoke/hohUkeV/hohukeV
pI
piyoke/pioke/pivoke/pihoke/pihukeV/pihUkeV
CU
Cuyoke/Cuoke/Cuvoke/Cuhoke/CuhukeV/CuhUkeV
uTa
uTayoke/uTaoke/uTahoke/uTavoke/uTahukeV/uTahUkeV
so
soiyoke/soyoke/sooke/sovoke/sohoke/sohukeV/sohUkeV
se
seyoke/seoke/sehoke/sevoke/sehukeV/sehUkeV
