Noun_m_e1
ladZikA
ladZiko/ladZikO/ladZikau
ladZikano/ladZikanO/ladZikanau
ladZiko/ladZikO/ladZikau
ladZikanO/ladZikano/ladZikanau
rAjA
rAjo/rAjO/rAjau
rAjo/rAjO/rAjau
rAjo/rAjO/rAjau
rAjano/rAjanO/rAjanau
Gara
Garo/GarO/Garau
Garo/GarO/Garau
Garo/GarO/Garau
Garano/GaranO/Garanau
Karca
Karco/KarcO/Karcau
Karco/KarcO/Karcau
Karco/KarcO/Karcau
Karcano/KarcanO/Karcanau
kavi
kavio/kaviau/kaviO
kavio/kaviau/kaviO
kavio/kaviau/kaviO
kavino/kavinau/kavinO
AxamI
Axamio/Axamiau/AxamiO
Axamio/Axamiau/AxamiO
Axamio/Axamiau/AxamiO
Axaminau/Axamino/AxaminO
sawru
sawruo/sawruau/sawruO
sawruo/sawruau/sawruO
sawruo/sawruau/sawruO
sawruno/sawrunau/sawrunO
AlU
Aluo/Aluau/AluO
Aluo/Aluau/AluO
Aluo/Aluau/AluO
Alunau/Aluno/AlunO
kuvAz
kuvoM/kuvOM/kuvauM/kuvoz/kuvOz/kuvauzkuoM/kuOM/kuaMu/kuoz/kuOz/kuazu
kuvoM/kuvOM/kuvauM/kuvoz/kuvOz/kuvauzkuoM/kuOM/kuaMu/kuoz/kuOz/kuazu
kuvoM/kuvOM/kuvauM/kuvoz/kuvOz/kuvauz/kuoM/kuOM/kuaMu/kuoz/kuOz/kuazu
kuvaznau/kuvaMnau/kuMvano/kuMvanO/kuzvano/kuzvanO/kuazno/kuaMno/kuaznau/kuaMnau/kuaznO/kuaMnO
gehUz
gehUzo/gehUMo/gehUzO/gehUMO/gehUzau/gehUMau
gehUzo/gehUMo/gehUzO/gehUMO/gehUzau/gehUMau
gehUzo/gehUMo/gehUzO/gehUMO/gehUzau/gehUMau
gehuzno/gehuMno/gehuznau/gehuMnau/gehuznO/gehuMnO
kroXa
kroXo/kroXO/kroXau
kroXo/kroXO/kroXau
kroXo/kroXO/kroXau
kroXo/kroXO/kroXau
lakaTo
lakaTo/lakaTau/lakaTO
lakaTano/lakaTono/lakaTanau/lakaTonau/lakaTanO/lakaTonO
lakaTo/lakaTau/lakaTO
lakaTano/lakaTono/lakaTanau/lakaTonau/lakaTanO/lakaTonO
sarasoM
sarasoMoM/sarasozoz/sarasoMOM/sarasozOzsarasoMauM/sarasozauz
sarasoMno/sarasoznau/sarasaMnau/sarasaznau/sarasaMOE/sarasaznO
sarasoMoM/sarasozoz/sarasoMOM/sarasozOzsarasoMauM/sarasozauz
sarasoMno/sarasozno/sarasaMnau/sarasaznau/sarasaMnO/sarasaznO
gosAIM
gosAIMo/gosAIzo/gosAIMauM/gosAIzauz/gosAIMOM/gosAIzOz
gosAIMo/gosAIzo/gosAIMauM/gosAIzauz/gosAIMOM/gosAIzOz
gosAIMo/gosAIzo/gosAIMauM/gosAIzauz/gosAIMOM/gosAIzOz
gosAIManau/gosAIzanau/gosAIMano/gosAIzano/gosAIManO/gosAIzanO
sonarA
sonaro/sonarau/sonarO
sonaro/sonarau/sonarO
sonaro/sonarau/sonarO
sonaranau/sonarano/sonaranO
