Noun_m_e
ladZikA
ladZike/ladZikai/ladZikE
ladZikane/ladZikanai/ladZikanE
ladZike/ladZikai/ladZikE
ladZikane/ladZikanai/ladZikanE
rAjA
rAje/rAjai/rAjE
rAje/rAjai/rAjE
rAje/rAjai/rAjE
rAjanai/rAjane/rAjanE
Gara
Gare/Garai/GarE
Gare/Garai/GarE
Gare/Garai/GarE
Garanai/Garane/GaranE
Karca
Karce/Karcai/KarcE
Karce/Karcai/KarcE
Karce/Karcai/KarcE
Karcanai/Karcane/KarcanE
kavi
kavie/kaviai/kaviE
kavie/kaviai/kaviE
kavie/kaviai/kaviE
kavine/kavinai/kavinE
AxamI
Axamie/Axamiai/AxamiE
Axamie/Axamiai/AxamiE
Axamie/Axamiai/AxamiE
Axaminai/Axamine/AxaminE
sawru
sawrue/sawruai/sawruE
sawrue/sawruai/sawruE
sawrue/sawruai/sawruE
sawrune/sawrunai/sawrunE
AlU
Alue/Aluai/AluE
Alue/Aluai/AluE
Alue/Aluai/AluE
Alunai/Alune/AlunE
kuvAz
kuveM/kuvEM/kuvaiM/kueM/kuvEM/kuvaiM/kuvez/kuvEz/kuvazi/kuez/kuEZ/kuaiz
kuveM/kuvEM/kuvaiM/kueM/kuvEM/kuvaiM/kuvez/kuvEz/kuvazi/kuez/kuEZ/kuaiz
kuveM/kuvEM/kuvaiM/kueM/kuvEM/kuvaiM/kuvez/kuvEz/kuvazi/kuez/kuEZ/kuaiz
kuvaznai/kuvaMnai/kuMvane/kuMvanE/kuzvane/kuzvanE/kuazne/kuaMne/kuaznai/kuaMnai/kuaznE/kuaMnE
gehUz
gehUze/gehUMe/gehUzE/gehUME/gehUzai/gehUMai
gehUze/gehUMe/gehUzE/gehUME/gehUzai/gehUMai
gehUze/gehUMe/gehUzE/gehUME/gehUzai/gehUMai
gehuzne/gehuMne/gehuznai/gehuMnai/gehuznE/gehuMnE
kroXa
kroXe/kroXE/kroXai
kroXe/kroXE/kroXai
kroXe/kroXE/kroXai
kroXe/kroXE/kroXai
lakaTo
lakaTe/lakaTai/lakaTE
lakaTane/lakaTone/lakaTanai/lakaTonai/lakaTanE/lakaTonE
lakaTe/lakaTai/lakaTE
lakaTane/lakaTone/lakaTanai/lakaTonai/lakaTanE/lakaTonE
sarasoM
sarasoMeM/sarasozez/sarasoMEM/sarasozEz/sarasoMaiM/sarasozaiz
sarasoMne/sarasoznai/sarasaMnai/sarasaznai/sarasaMnE/sarasaznE
sarasoMeM/sarasozez/sarasoMEM/sarasozEz/sarasoMaiM/sarasozaiz
sarasoMne/sarasozne/sarasaMnai/sarasaznai/sarasaMnE/sarasaznE
gosAIM
gosAIMe/gosAIze/gosAIMaiM/gosAIzaiz/gosAIMEM/gosAIzEz
gosAIMe/gosAIze/gosAIMaiM/gosAIzaiz/gosAIMEM/gosAIzEz
gosAIMe/gosAIze/gosAIMaiM/gosAIzaiz/gosAIMEM/gosAIzEz
gosAIManai/gosAIzanai/gosAIMane/gosAIzane/gosAIManE/gosAIzanE
sonarA
sonare/sonarai/sonarE
sonare/sonarai/sonarE
sonare/sonarai/sonarE
sonaranai/sonarane/sonaranE
