Noun_f_e1
ladZakI
ladZakio/ladZakiau/ladZakiO
ladZakino/ladZakinau/ladZakinO
ladZakio/ladZakiau/ladZakiO
ladZakino/ladZakinau/ladZakinO
mAI
mAio/mAiau/mAiO/maio/maiau/maiO/mAyio/mAyiau/mAyiO
mAino/mAinau/mAinO/maino/mainau/mainO/mAyano/mAyanau/mAyanO
mAio/mAiau/mAiO/maio/maiau/maiO/mAyio/mAyiau/mAyiO
mAino/mAinau/mAinO/maino/mainau/mainO/mAyano/mAyanau/mAyanO
rAwa
rAwo/rAwO/rAwau
rAwo/rAwO/rAwau
rAwo/rAwO/rAwau
rAwano/rAwanO/rAwanau
rawi
rAwio/rAwiau/rAwiO
rAwio/rAwiau/rAwiO
rAwio/rAwiau/rAwiO
rAwino/rAwinau/rawinO
Orawa
Orawo/Orawau/OrawO
Orawano/Orawanau/OrawanaO/Orawino
Orawo/Orawau/OrawO
Orawano/Orawanau/OrawanaO/Orawino
BAsA
BAso/BAsO/BAsau/Baso/Basau/BasO
BAso/BAsO/BAsau/Baso/Basau/BasO
BAso/BAsO/BAsau/Baso/Basau/BasO
BAsano/BAsanO/BAsanau/Basano/Basanau/BasanO
gudZiyA
gudZiyo/gudZiyO/gudZiyau/gudZio/gudZiau/gudZiO
gudZiyo/gudZiyO/gudZiyau/gudZio/gudZiau/gudZiO
gudZiyo/gudZiyO/gudZiyau/gudZio/gudZiau/gudZiO
gudZiyano/gudZiyanO/gudZiyanau/gudZiano/gudZianO/gudZianau
sakwi
sakwio/sakwiau/sakwiO
sakwio/sakwiau/sakwiO
sakwio/sakwiau/sakwiO
sakwino/sakwinau/sakwinaO
qwu
qwuo/qwuau/qwuO
qwuo/qwuau/qwuO
qwuo/qwuau/qwuO
qwuno/qwuanau/qwunO
bahU
bahuo/bahuau/bahuO
bahuno/bahunau/bahunO
bahuo/bahuau/bahuO
bahuno/bahunau/bahunO
lO
lOVo/lOVO/lOau
lOno/lOnO/lOnau
lOVo/lOVO/lOau
lOno/lOnO/lOnau
mAz
mAzau/mAzO/mAzo/mAMau/mAMO/mAMo
mAzvanau/mAzvanO/mAzvano/mAMvanau/mAMvanO/mAMvano/mAzyanau/mAzyanO/mAzyano/mAMyanau/mAMyanO/mAMyano/mAzino/mAzinau/mAzinO/mAMzino/mAMzinau/mAMzinO
mAzau/mAzO/mAzo/mAMau/mAMO/mAMo
mAzvanau/mAzvanO/mAzvano/mAMvanau/mAMvanO/mAMvano/mAzyanau/mAzyanO/mAzyano/mAMyanau/mAMyanO/mAMyano/mAzino/mAzinau/mAzinO/mAMzino/mAMzinau/mAMzinO
Poto
Potoo/Potoau/PotoO
Potoo/Potoau/PotoO
Potoo/Potoau/PotoO
Potono/Potanau/PotanO
PotoM
PotoMo/Potozo/PotoMau/Potazau/PotoMO/PotozO
PotoMo/Potozo/PotoMau/Potazau/PotoMO/PotozO
PotoMo/Potozo/PotoMau/Potazau/PotoMO/PotozO
PotoMno/Potozno/Potoznau/PotoMnau/PotoMnO/PotoznO
BUiM
BUiMo/BUizo/BUiMau/BUizau/BUiMO/BUizO
BUiMano/BUizano/BUiManau/BUizanau/BUiManO/BUizanO
BUiMo/BUizo/BUiMau/BUizau/BUiMO/BUizO
BUiMano/BUizano/BUiManau/BUizanau/BUiManO/BUizanO
BOM
BOMo/BOzo/BOzuo/BOMuo/BOMO/BOzO/BOzuO/BOMuO/BOMau/BOzau/BOzuau/BOMuau
BOMano/BOzano/Bazuano/BaMuano/BOManau/BOzanau/Bazuanau/BaMuanau/BOManO/BOzanO/BazuanO/BaMuanO
BOMo/BOzo/BOzuo/BOMuo/BOMO/BOzO/BOzuO/BOMuO/BOMau/BOzau/BOzuau/BOMuau
BOMano/BOzano/Bazuano/BaMuano/BOManau/BOzanau/Bazuanau/BaMuanau/BOManO/BOzanO/BazuanO/BaMuanO
BarasAIM
BarasAiMoM/BarasAizoz/BarasaiMauM/Barasaizauz/BarasAiMOM/BarasAizOz
BarasAiMno/BarasAizno/BarasAiMnauM/BarasAiznauz/BarasaiMno/Barasaizno/BarasaiMnauM/Barasaiznauz
BarasAiMoM/BarasAizoz/BarasaiMauM/Barasaizauz/BarasAiMOM/BarasAizOz
BarasAiMno/BarasAizno/BarasAiMnauM/BarasAiznauz/BarasaiMno/Barasaizno/BarasaiMnauM/Barasaiznauz
Bora
Boro/BorO/Borau
Boro/BorO/Borau
Boro/BorO/Borau
Borano/BoranO/Boranau
