Noun_f_rednt_e
ladZakiyA
ladZakiye/ladZakiyai/ladZakiyE
ladZakiyanai/ladZakiyane/ladZakiyanE/ladZakianai/ladZakiane/ladZakianE
ladZakiye/ladZakiyai/ladZakiyE
ladZakiyanai/ladZakiyane/ladZakiyanE/ladZakianai/ladZakiane/ladZakianE
maiyA
maiye/maiyai/maiyE/maie/maiai/maiE
maiyanai/maiyane/maiyanE/maianai/maiane/maianE
maiye/maiyai/maiyE/maie/maiai/maiE
maiyanai/maiyane/maiyanE/maianai/maiane/maianE
rawiyA
rawiye/rawiyai/rawiyE/rawie/rawiai/rawiE
rawiye/rawiyai/rawiyE/rawie/rawiai/rawiE
rawiye/rawiyai/rawiyE/rawie/rawiai/rawiE
rawiyanai/rawiyane/rawiyanE/rawiane/rawianai/rawianE
OrawiyA
Orawiye/Orawiyai/OrawiyE/Orawie/Orawiai/OrawiE
Orawiyanai/Orawiyane/OrawiyanE/Orawiane/Orawianai/OrawianE
Orawiye/Orawiyai/OrawiyE/Orawie/Orawiai/OrawiE
Orawiyanai/Orawiyane/OrawiyanE/Orawiane/Orawianai/OrawianE
BasavA
Basave/Basavai/BasavE
Basave/Basavai/BasavE
Basave/Basavai/BasavE
Basavanai/Basavane/BasavanE
lauvA
lauve/lauvai/lauvE/laue/lauai/lauE
lauvane/lauvanE/lauvanai/lauane/lauanai/laquanE
lauve/lauvai/lauvE/laue/lauai/lauE
lauvane/lauvanE/lauvanai/lauane/lauanai/laquanE
gudZiyavA
gudZiyavai/gudZiyave/gudZiyavE/gudZiavai/gudZiave/gudZiavE
gudZiyavai/gudZiyave/gudZiyavE/gudZiavai/gudZiave/gudZiavE
gudZiyavai/gudZiyave/gudZiyavE/gudZiavai/gudZiave/gudZiavE
gudZiyavanai/gudZiyavane/gudZiyavanE/gudZiavane/gudZiavanai/gudZiavanE
sakwiyA
sakwiye/sakwiyai/sakwiyE
sakwiye/sakwiyai/sakwiyE
sakwiye/sakwiyai/sakwiyE
sakwiyanai/sakwiyane/sakwiyanE
bahuvA
bahuve/bahuvai/bahuvE
bahuve/bahuvai/bahuvE
bahuve/bahuvai/bahuvE
bahuvanai/bahuvane/bahuvanE
qwuvA
qwuve/qwuvE/qwuvai
qwuve/qwuvE/qwuvai
qwuve/qwuvE/qwuvai
qwuvane/qwuvanE/qwuvnai
BoravA
Borave/Boravai/BoravE
Borave/Boravai/BoravE
Borave/Boravai/BoravE
Boravanai/Boravane/BoravanE
BarasaiMyAM
BarasaiMyeM/BarasaiMyEM/BarasaiMyaiM/BarasaiMyez/BarasaiMyEz/BarasaiMyaiz/BarasaizyeM/BarasaizyEM/BarasaizyaiM/Barasaizyez/BarasaizyEz/Barasaizyaiz
BarasaiMyaneM/BarasaiMyanaiM/BarasaiMyanEM/BarasaiMyanez/BarasaiMyanaiz/BarasaiMyanEz/Barasaizyanez/Barasaizyanaiz/BarasaizyanEz/BarasaizyaneM/BarasaizyanaiM/BarasaizyanEM
BarasaiMyeM/BarasaiMyEM/BarasaiMyaiM/BarasaiMyez/BarasaiMyEz/BarasaiMyaiz/BarasaizyeM/BarasaizyEM/BarasaizyaiM/Barasaizyez/BarasaizyEz/Barasaizyaiz
BarasaiMyaneM/BarasaiMyanaiM/BarasaiMyanEM/BarasaiMyanez/BarasaiMyanaiz/BarasaiMyanEz/Barasaizyanez/Barasaizyanaiz/BarasaizyanEz/BarasaizyaneM/BarasaizyanaiM/BarasaizyanEM
BOMvAM
BOMveM/BOzvez/BOMvaiM/BOzvaiz/BOMvEM/BOzvEz/BOMvez/BOzveM/BOMvaiz/BOzvaiM/BOMvEz/BOzvEM
BOMvane/BOMvanai/BOMvanai/Bozvane/Bozvanai/BozvanE
BOMveM/BOzvez/BOMvaiM/BOzvaiz/BOMvEM/BOzvEz/BOMvez/BOzveM/BOMvaiz/BOzvaiM/BOMvEz/BOzvEM
BOMvane/Bozvane/BOMvanai/BOzvanai/BOMvanE/BozvanEe/
PotoM
PotoMiyeM/Potoziyez/PotoMiyez/PotoziyeM/PotoMiyEM/PotoziyEz/PotoMiyEz/PotoziyEM/PotoMiyaiM/Potoziyaiz/PotoMiyaiz/PotoziyaiM
PotoMiyeM/Potoziyez/PotoMiyez/PotoziyeM/PotoMiyEM/PotoziyEz/PotoMiyEz/PotoziyEM/PotoMiyaiM/Potoziyaiz/PotoMiyaiz/PotoziyaiM
PotoMiyeM/Potoziyez/PotoMiyez/PotoziyeM/PotoMiyEM/PotoziyEz/PotoMiyEz/PotoziyEM/PotoMiyaiM/Potoziyaiz/PotoMiyaiz/PotoziyaiM
PotoMiyane/Potoziyane/PotoMiyanai/Potoziyanai/PotoMiyanE/PotoziyanE
BuiMyAM
BuiMyeM/Buizyez/BuiMyez/BuizyeM/BuiMyaiM/Buizyaiz/BuiMyaiz/BuizyaiM/BuiMyEM/BuizyEz/BuiMyEz/BuizyEM
BuiMyanai/Buizyanai/BuiMyane/Buizyane/BuiMyanE/BuizyanE
BuiMyeM/Buizyez/BuiMyez/BuizyeM/BuiMyaiM/Buizyaiz/BuiMyaiz/BuizyaiM/BuiMyEM/BuizyEz/BuiMyEz/BuizyEM
BuiMyanai/Buizyanai/BuiMyane/Buizyane/BuiMyanE/BuizyanE
PotoiyA
Potoiye/Potoiyai/PotoiE
Potoiye/Potoiyai/PotoiE
Potoiye/Potoiyai/PotoiE
Potoiyane/Potyanai/PotanE
