Noun_f_e
ladZakI
ladZakie/ladZakiai/ladZakiE
ladZakine/ladZakinai/ladZakinE
ladZakie/ladZakiai/ladZakiE
ladZakine/ladZakinai/ladZakinE
mAI
mAie/maie/maiai/maiE/mAiE/mAiai/mAyie/mAyiai/mAyE
mAine/mAinai/mAinE/maine/mainai/mainE/mAyane/mAyanai/mAyanE
mAie/maie/maiai/maiE/mAiE/mAiai/mAyie/mAyiai/mAyE
mAine/mAinai/mAinE/maine/mainai/mainE/mAyane/mAyanai/mAyanE
rAwa
rAwe/rAwai/rAwE
rAwe/rAwai/rAwE
rAwe/rAwai/rAwE
rAwane/rAwanai/rAwanE
rAwi
rAwie/rAwie/rAwiai
rAwie/rAwie/rAwiai
rAwie/rAwie/rAwiai
rAwine/rAwinai/rawine
Orawa
Orawe/Orawai/OrawE
Orawane/Orawanai/OrawanE/Orawine
Orawe/Orawa/OrawE
Orawane/Orawanai/OrawanE/Orawine
BAsA
BAse/BAsai/BAsE/Base/Basai/BasE
BAse/BAsai/BAsE/Base/Basai/BasE
BAse/BAsai/BAsE/Base/Basai/BasE
BAsane/BAsanai/BAsanE/Basanai/Basane/BasanE
gudZiyA
gudZiye/gudZie/gudZiyai/gudZiai/gudZiE/gudZiyE
gudZiye/gudZie/gudZiyai/gudZiai/gudZiE/gudZiyE
gudZiye/gudZie/gudZiyai/gudZiai/gudZiE/gudZiyE
gudZiyanai/gudZiyane/gudZianai/gudZiane/gudZiyanE/gudZianE
sakwi
sakwie/sakwiai/sakwiE
sakwie/sakwiai/sakwiE
sakwie/sakwiai/sakwiE
sakwine/sakwinai/sakwinaE
qwu
qwue/qwuai/qwuE
qwue/qwuai/qwuE
qwue/qwuai/qwuE
qwune/qwuanai/qwunE
bahU
bahue/bahuai/bahuE
bahune/bahunai/bahunE
bahue/bahuai/bahuE
bahune/bahunai/bahunE
lO
lOe/lOai/lOE
lOne/lOnai/lOnE
lOe/lOai/lOE
lOne/lOnai/lOnE
mAz
mAzai/mAzE/mAze/mAMai/mAME/mAMe
mAzvanai/mAzvanE/mAzvane/mAMvanai/mAMvanE/mAMvane/mAzyanai/mAzyanE/mAzyane/mAMyanai/mAMyanE/mAMyane/mAzine/mAzinai/mAzinE/mAMzine/mAMzinai/mAMzinE
mAzai/mAzE/mAze/mAMai/mAME/mAMe
mAzvanai/mAzvanE/mAzvane/mAMvanai/mAMvanE/mAMvane/mAzyanai/mAzyanE/mAzyane/mAMyanai/mAMyanE/mAMyane/mAzine/mAzinai/mAzinE/mAMzine/mAMzinai/mAMzinE
Poto
Potoe/Potoai/PotoE
Potoe/Potoai/PotoE
Potoe/Potoai/PotoE
Potone/Potonai/PotonE
PotoM
Potoze/Potazai/PotozE/PotoMe/PotoMai/PotoME
Potoze/Potazai/PotozE/PotoMe/PotoMai/PotoME
Potoze/Potazai/PotozE/PotoMe/PotoMai/PotoME
Potozne/Potoznai/PotoznE/PotoMne/PotoMnai/PotoMnE
BUiM
BUiMe/BUize/BUiMai/BUizai/BUiME/BUizE
BUiMane/BUizane/BUiManai/BUizanai/BUiManE/BUizanE
BUiMe/BUize/BUiMai/BUizai/BUiME/BUizE
BUiMane/BUizane/BUiManai/BUizanai/BUiManE/BUizanE
BOM
BOMe/BOze/BOzue/BOMue/BOME/BOzE/BOzuE/BOMuE/BOMai/BOzai/BOzuai/BOMuai
BOMane/BOzane/Bazuane/BaMuane/BOManai/BOzanai/Bazuanai/BaMuanai/BOManE/BOzanE/BazuanE/BaMuanE
BOMe/BOze/BOzue/BOMue/BOME/BOzE/BOzuE/BOMuE/BOMai/BOzai/BOzuai/BOMuai
BOMane/BOzane/Bazuane/BaMuane/BOManai/BOzanai/Bazuanai/BaMuanai/BOManE/BOzanE/BazuanE/BaMuanE
BarasAIM
BarasAiMeM/BarasAizez/BarasaiMaiM/Barasaizaiz/BarasAiMEM/BarasAizEz
BarasAiMne/BarasAizne/BarasAiMnaiM/BarasAiznaiz/BarasaiMne/Barasaizne/BarasaiMnaiM/Barasaiznaiz
BarasAiMeM/BarasAizez/BarasaiMaiM/Barasaizaiz/BarasAiMEM/BarasAizEz
BarasAiMne/BarasAizne/BarasAiMnaiM/BarasAiznaiz/BarasaiMne/Barasaizne/BarasaiMnaiM/Barasaiznaiz
Bora
Bore/Borai/BorE
Bore/Borai/BorE
Bore/Borai/BorE
Borane/Boranai/BoranE
