optative_ilA
KA
KAilA
KAilA/KAliM
KAla/KAlAV/KAlaV
KAla/KAlaM/KAlaz/KAliM/KAlEM
KaVlA/KAlAV/KAlA
KAlana
KAilA
KAilA/KAliM
KAlU/KAlu/KAli
KAlU/KAliM/KAlina
KAlE/KAlai
KAlina
uTa
uTIlA/uTaVli/uTaVlI
uTIlA/uTaVli/uTaVlI
uTala
uTala/uTalaz/uTaVlaM/uTaVliM/uTaVlEM
uTelA/uTaVlA/uTalA
uTelana/uTaVlana
uTIlA/uTaVli/uTaVlI
uTIlA/uTaVli/uTaVlI
uTaVlU/uTelU/uTaVlu/uTelu
uTaVlU/uTelU/uTaVlu/uTelu/uTaVliM
uTaVlai/uTeli
uTaVlina/uTelina
pI
piilA/piyeli/pIilA/pIyeli
piilA/piyeli/pIilA/pIyeli
piyaVla/piaVla
piyaVla/piaVla/piaVliM/piyaVliM/piyaVlaz/piana/piyena/piaVlana/piyelana
piyaVlA/piaVlA/pialA/piyalA/pIalA/pIyalA
piyaVlana/piaVlana/piana/piyena/piyelana
piilA/piyeli/pIilA/pIyeli
piilA/piyeli/pIilA/pIyeli
piyaVlu/piaVlu/piyaVlU/piaVlU
piyaVlu/piaVlu/piyaVlU/piaVlU/piaVliM/piyaVliM/piyaVliz
piyele/piele/piyaVle/piaVle/piyaVlai/piaVlai
piyelina/pielina/piyaVlina/piaVlina
kara
karilA/kareli/karIlA
karilA/kareli/karIlA
karaVla/karela
karaVla/karela/karelA/kareliM/kareniM
karaVlA/karelA/karalA
karalaVna/karelana/karaVna/karalana/karana
karilA/kareli/karIlA
karilA/kareli/karIlA
karaVlu/karaVlU/karelu/karelU
karaVlu/karaVlU/karelu/karelU/kareliM/karaVliM/kareniM
karaVlai/karelai/karele
karaVlina/karelina/karaVni
le
lehilA/levaVni/leVni
lehilA/levaVni/leVni
lela/levaVla
lela/levaVla/lelaz/levaVlaz/levaVliz/leveliz/leveniM
levaVlA/levelA/lelA
levaVna/levena/leVna/leMVna
lehilA/levaVni/leVni
lehilA/levaVni/leVni
lelu/lelU/levaVlu/levaVlU
lelu/lelU/levaVlu/levaVlU/leliMna/levaVlaz/levaVliz/leveliz/leveniM
levaVlai/levelai/lelai
levaVni/leveni/leni/leMni
xe
xehilA/xeVni
xehilA/xeVni
xela/xevaVla/xevela
xeVla/xevaVla/xevela/xehilA/xeveni/xeveliM/xelaz/xeVna
xevaVlA/xelA/xevelA
xevaVna/xevena/xelana/xena
xehilA/xeVni
xehilA/xeVni
xeVlu/xeVlU/xevaVlu/xevaVlU/xevelu/xevelU
xeVlu/xeVlU/xevaVlu/xevaVlU/xevelu/xevelU/xehilA/xeveni/xeveliM/xelina/xeVni
xelai/xeVle/xevelai
xevaVni/xeveni/xelina/xeni
CU
CuilA/Cuveni/CUilA/CUveni
CuilA/Cuveni/CUilA/CUveni
CuvaVla/Cuvela/CUvaVla/CUvela
CuvaVla/Cuvela/CUvaVla/CUvela/CuveliM/CuvaniM
CuaVlA/CuvaVlA/CUaVlA/CUvaVlA/CuvalA/CUvalA
CuaVna/CuvaVna/CUaVna/CUvaVna/CuvaVlana/CuaVlana
CuilA/Cuveni/CUilA/CUveni
CuilA/Cuveni/CUilA/CUveni
CuvaVlu/Cuvelu/CUvaVlu/CUvelu/CuvaVlU/CuvelU/CUvaVlU/CUvelU/Cuvele
CuvaVlu/Cuvelu/CUvaVlu/CUvelu/CuvaVlU/CuvelU/CUvaVlU/CUvelU/CuveliM/CuvaniM
CuaVli/CuvaVli/CUaVli/CUvaVli/CuvaVlai/CuaVlai/Cuvele
CuaVni/CuvaVni/CUaVni/CUvaVni/CuvaVlani/CuaVlina
ho
hoilA/holiM
hoilA/holiM
hoVla
hoVla/holaM/holaz/holiM/holEM
hoVlA/holA
holana
hoilA
hoilA/holiM
holU/holu
holU/holiM
holE/holai
holina
so
soilA/sovani/sovaVli
soilA/sovani/sovaVli
sovaVla/soaVla
sovaVla/sovaVliM/sovana/sovalaM/sovalaz
soaVlA/sovaVlA/sovelA/soVlA/soalA
soaVlana/sovaVlana/sovelana/soVlana/sovaVna
soilA/sovani/sovaVli
soilA/sovani/sovaVli
sovaVlu/sovaVlU/soaVlu/soaVlU
sovaVlu/sovaVlU/soaVlu/soaVlU/sovaVliM/sovani/sovaliM/sovaliz
sovaVlai/sovelai/soVlai
sovaVlina/sovelina/soVlina/sovaVni
se
seilA/sevani/sevaVli
seilA/sevani/sevaVli
sevaVla/seaVla
sevaVla/sevaVliM/sevana/sevalaM/sevalaz
seaVlA/sevaVlA/sevelA/seVlA/sealA
seaVlana/sevaVlana/sevelana/seVlana/sevaVna
seilA/sevani/sevaVli
seilA/sevani/sevaVli
sevaVlu/sevaVlU/seaVlu/seaVlU
sevaVlu/sevaVlU/seaVlu/seaVlU/sevaVliM/sevani/sevaliM/sevaliz
sevaVlai/sevelai/seVlai
sevaVlina/sevelina/seVlina/sevaVni
