Pres_Prog_Asp_e1_wa
KA
KAwo/KawO/KAwau
pI
piyawo/piyawO/piyawau/piawo/piawO/piawau
uTa
uTawo/uTawO/uTawau
kara
karawo/karawO/karawau
CU
CUawo/CUawO/CUawau/CUvawo/CUvawO/CUvawau/Cuawo/CuawO/Cuawau/Cuvawo/CuvawO/Cuvawau
ho
howo/howO/howau/hoawo/hoawO/hoawau/hovawo/hovawO/hovawau
le
lewo/lewO/lewau/levawo/levawO/levawau
xe
xewo/xewO/xewau/xevawo/xevawO/xevawau
se
seawo/seawO/seawau/sevawo/sevawO/sevawau
so
soawo/soawO/soawau/sovawo/sovawO/sovawau
