Pst_Perf_Prtcpl_yala
KA
KAyala/KAila
pI
piyala/piala/pIyala/pIala
le
lela/lehala/lihala/levala/leyala
xe
xela/xehala/xihala/xevala/xeyala
kara
karala/kaila/kayala
ho
hola/hoyala/hoala/huvala/huala/hovala/hUvala/hUala/hoila
CU
Cuala/Cuvala/Cuyala/CUala/CUvala/CUyala
se
seala/seyala/sevala/seila
so
soala/soyala/sovala/soila
uTa
uTala/uTela
