PstPerf_Plus_Aux_e_yale
KA
Kayalahi/KailahI/Kailahi/KayalahI/KailE/KayalE
kara
kailahi/kailahI/kayalahi/kailE/kayalE
le
lelahi/lelahI/lehalahi/lahalahI/lihalahi/lihalahI
xe
xelahi/xelahI/xehalahi/xehalahI/xihalahi/xihalahI
ho
hoilahi/hoilahI/hoyalahi/hoyalahI/Bailahi/BayalahI/Bayalahi/BailahI
CU
Cualahi/CuèalahI/CUalahi/CUalahI/Cuvalahi/CuvalahI/CUvalahi/CUvalahI
uTa
uTalahi/uTalahI/uTalai/uTalE
pI
piyalahi/piyalahI/pialahi/pIalahI
se
sealahi/sealahI/seyalahi/seyalahI
so
sovalahi/sovalahI/soalahi/soalahI
