PstPerf_Minus_Aux_ila1
jA
gaili/gayali/gayalI
gaili/gayali/gayalI
gaila/gayala/gayalaV/gailA
gaila/gailIM/gailiM/gailana/gayalana/gailA
gailesa/gailasa/gayalasa/gayalesa/gayala/gaila
gailana/gainaV/gailaM/gailaz/gailena/gayalana
gaili/gailI
gaili/gailI
gailU/gailu/gaili/gayali/gayalI
gailU/gailu/gailina/gailiM
gailesa/gaila
gailina/gaini/gainI
