PstPerf_Plus_Aux_e1_yale
KA
KailahUM/KailahuM/KayalahUM/KayalahuM/KailahUz/Kailahuz/Kailo/KailO/Kailau
kara
kailahUM/kailahuM/kayalahUM/kayalahuM/kailahUz/kailahuz/kailo/kailO/kailau
le
lelahuM/lelahuz/lelahUM/lelahUz/lahalahUM/lahalahUz/lahalahuz/lehalahUz/lehalahuz/lihalahUz/lihalahuz/lehalo/lehalO/lehalau/lihalo/lihalO/lihalau
xe
xelahuM/xelahuz/xelahUM/xelahUz/xihalahUM/xihalahUz/xihalahuz/xehalahUz/xehalahuz/xehalo/xehalO/xehalau
ho
hoilahUz/hoilahUM/hoilahuM/hoilahuz/hoyalahUz/hoyalahUM/hoyalahuM/hoyalahuz/BailahUz/BailahUM/BailahuM/Bailahuz/BayalahUz/BayalahUM/BayalahuM/Bayalahuz/hoilo/hoilO/hoilau/Bailo/BailO/Bailau
CU
Cualahuz/CualahUz/CualahuM/CualahUM/Cuvalahuz/CuvalahUz/CuvalahuM/CuvalahUM/Cuvalo/CuvalO/Cuvalau/Cualo/CualO/Cualau/Cualaho/CualahO/Cualahau
uTa
uTalahuz/uTalahuM/uTalahUz/uTalahUM/uTalo/uTalO/uTalau/uTalaho/uTalahO/uTalahau
pI
piyalahuz/piyalahuM/piyalahUz/piyalahUM/piyalaho/piyalahO/piyalahau/pialahuz/pialahuM/pialahUz/pialahUM/pialaho/pialahO/pialahau/pilahUz/pilahuz/pilahUM/pilahuM/pialo/pialO/pialau/piyalo/piyalO/piyalau
se
seyalahuz/seyalahuM/seyalahUz/seyalahUM/seyalaho/seyalahO/seyalahau/sealahuz/sealahuM/sealahUz/sealahUM/sealaho/sealahO/sealahau/selahUz/selahuz/selahUM/selahuM/sealo/sealO/sealau/seyalo/seyalO/seyalau/sevalahuz/sevalahuM/sevalahUz/sevalahUM/sevalaho/sevalahO/sevalahau/sevalo/sevalO/sevalau
so
soalahuz/soalahuM/soalahUz/soalahUM/soalaho/soalahO/soalahau/solahUz/solahuz/solahUM/solahuM/soalo/soalO/soalau/sovalahuz/sovalahuM/sovalahUz/sovalahUM/sovalaho/sovalahO/sovalahau/sovalo/sovalO/sovalau
