subj
KA
KAiM/KAiz
KailaV/KAva
KAiM/KAiz/KAzya
KAya
KAiM/KAiz
KA
KAiM/KAiz/KAzya
KAzya
-
-
KAiM/KAiz/KAzya
-
kara
kariM/karIM/kariz/karIz
kailaV/kayalaV
kariM/karIM/kariz/karIz/karEM
karai/kare
kariM/karIM/kariz/karIz
karaV
kariM/karIM/kariz/karIz/karEM
karEM
-
-
kariM/karIM/kariz/karIz/karEM
-
le
leiM/leiz/lehiM/lehIM
lehalaV/lihalaV/lelaV/lehale
leiM/leiz/lehiM/lehIM
lei
leiM/leiz/lehiM/lehIM
laV/lA
leiM/leiz/lehiM/lehIM/leMi/laMi/lazi
leMi/laMi/lazi
-
-
leiM/leiz/lehiM/lehIM/leMi/laMi/lazi
-
ho
hoiM/hoiz
hoilaV
hovaiM/hoMi
hoya
hoiM/hoiz
hova
hovaiM/hoMi
hoveM/hovez/hoMve/hozve
-
-
hoveM/hovez/hoMve/hozva/hoMya/hozya
-
pI
pihiM/pihIM
piyalaV/pIyalaV/piyaVle/piaVle/piyale/piale
piiM/piiz/pihiM/pihIM/piyaz/pIyaz/piyaM/pIyaM
piyai/piaya
piiM/piiz/pihiM/pihIM
piyaV/piu/pia
piiM/piiz/pihiM/pihIM/piyaz/pIyaz/piyaM/pIyaM
piiM/piiz/pihiM/pihIM
-
-
piiM/piiz/pihiM/pIhIM/pIMi/pIzi
-
CU
CUiM/CUiz/CUhiM/CuhIM/CuiM/Cuiz
CUalaV/CualaV
CUiM/CUiz/CUhiM/CUhIM/CUyaz/Cuyaz/CUyaM/CuyaM/CUaiM/CUaiz/CUahiM/CUahIM/CUayaz/Cuayaz/CUayaM/CuayaM/CUvaiM/CUvaiz/CUvahiM/CUvahIM/CUvayaz/Cuvayaz/CUvayaM/CuvayaM
CUvai/Cuvai/CUai/Cuai
CUiM/CUiz/CUhiM/CUhIM/CuiM/CuhiM/CuhIM
CUvaV/CUvA/Cua/CUa
CUiM/CUiz/CUhiM/CUhIM/CUyaz/Cuyaz/CUyaM/CuyaM/CUaiM/CUaiz/CUahiM/CUahIM/CUayaz/Cuayaz/CUayaM/CuayaM/CUvaiM/CUvaiz/CUvahiM/CUvahIM/CUvayaz/Cuvayaz/CUvayaM/CuvayaM
CUveM/CuveM/CUvez/Cuvez
-
-
CUiM/CUiz/CUhiM/CUhIM/CUyaz/Cuyaz/CUyaM/CuyaM/CUaiM/CUaiz/CUahiM/CUahIM/CUayaz/Cuayaz/CUayaM/CuayaM/CUvaiM/CUvaiz/CUvahiM/CUvahIM/CUvayaz/Cuvayaz/CUvayaM/CuvayaM
-
uTa
uTIM/uTiM/uTIz/uTiz
uTalaV
uTIM/uTiM/uTIz/uTiz/uTEM/uTaiz/uTaiM
uTai/uTE
uTIM/uTiM/uTIz/uTiz
uTa/uTA
uTaiM/uTEM
uTaiM/uTaiz/uTEM
-
-
uTaiM/uTaiz/uTEM
-
so
soiM/soiz
soaV/sovaV
soiM/soiz
sovai/sovE
soiM/soiz
soaV/sovaV
soiM/soiz/sovaiz/sovaiM
soiM/soiz/sovaiz/sovaiM
-
-
soiM/soiz/sovaiz/sovaiM
-
se
seiM/seiz
seaV/sevaV
seiM/seiz/sevaM
sevai/sevE
seiM/seiz
seaV/sevaV/sevAV
seiM/seiz/sevaiz/sevaiM
seiM/seiz/sevaiz/sevaiM
-
-
seiM/seiz/sevaiz/sevaiM
-
