Adj_All_e1
amIra
amIrau/amIro/amIrO
kariyA
kariyo/kariyO/kariyau/kario/kariO/kariau
gora
goro/gorO/gorau
nIlA
nIlo/nIlO/nIlau
pIyara
pIyaro/pIyarO/pIyarau/pIaro/pIarO/pIarau
asamAnI
asamaniyo/asamaniyO/asamaniyau/asamanio/asamaniO/asamaniau
aura
auro/aurO/aurau/avaro/avarO/avarau
cAlU
caluo/caluO/caluau/caluvo/caluvO/caluvau/cAluo/cAluO/cAluau/cAluvo/cAluvO/cAluvau
javAz
javoz/javoM/javazuM/javaMuz/javazuz/javaMuM/javazu/javaMu
BaxaIz
BaxaiMauM/Baxaizauz/BaxaiMauz/BaxaizauM/BaxaiMoM/Baxaizoz/BaxaiMoz/BaxaizoM/BaxaiMyauM/Baxaizyauz/BaxaiMyoM/Baxaizyoz/BaxaiMyoz/BaxaizyoM/BaxaizyauM/BaxaiMyauz
aPajUM
aPajuMvauM/aPajuMvauz/aPajuzvauM/aPajuzvauz/aPajuMoM/aPajuzoz/aPajuMoz/aPajuzoM
ekasOM
ekasOMvoM/ekasOzvoz/ekasOMvoz/ekasOzvoM/ekasoMvauM/ekasOzvauz/ekasOMvauz/ekasOzvauM
abuxXi
abuxXio/abuxXiyo/abuxXiau/abuxXiyau
asawru
asawruvau/asawruo/asawruau
aBE
aBEyau/aBEyo
jIro
jIrovau/jIrauvo
