Adj_case_e
aneka
aneko/anekO/aneke/anekai
aneko/anekO/aneke/anekai
kai
kaiyo/kaiyO/kaiye/kaie
kaiyo/kaiyO/kaiye/kaie
kaI
kaiyo/kaiyO/kaiye/kaie
kaiyo/kaiyO/kaiye/kaie
bIsa
bIsana/bisana/bIsoM/bisiyana/bisiana/bisiyoM
bIsana/bisana/bIsoM/bisiyana/bisiana/bisiyoM
ikAnabe
ikAnabevana
ikAnabevana
xonoM
xonoM/xunno/xunnau/xUnau/xUnno/xunnO
xonoM/xunno/xunnau/xUnau/xUnno/xunnO
saba
sabE/saBE/sabahi/sabahI/saBahi/saBahI/sabai
sabE/saBE/sabahi/sabahI/saBahi/saBahI/sabai
sEkadZoM
sEkadZoM/sEkadZana
sEkadZoM/sEkadZana
sO
sauvana
sauvana
