Adv_Time_e_wai
KA
KAwai/Kaiwai/KAwE/KEwe/Kaiwo/Kaiwau
pI
piyawai/piawai/piawe/piyawe/piawE/piyawE/pIyawai/pIawai/pIawe/pIyawe/pIawE/pIyawE/piyawo
uTa
uTawai/uTewai/uTawE/uTewE/uTawo
kara
karawai/karawE/karawo
CU
Cuawai/Cuvawai/CUawai/CUvawai/CuawE/CuvawE/CUawE/CUvawE/CUvawo/Cuvawo/Cuwo/CUwo
ho
howai/hoawai/hovawai/howE/hoawE/hovawE/hovawo/howo
le
lewai/levawai/lewE/levawE/lewo
xe
xewai/xevawai/xewE/xevawE/xewo
se
seawai/sevawai/sewE/seawE/sevawE/sewo
so
soawai/sovawai/sowE/soawE/sovawE/sowo
