Advrb_e1
aba
abbau/abbo/abbO/aBahiyoM/aBahio/abahiyoM/abahio/aBiyoM/aBio/abahu/abaho
kala
kAlho/kalhUz/kalhiyoM/kAlahuz/kalhio
Aja
Ajo/ajahuz/ajuo/ajuvo
parasoM
parasahuz/parasaoM/parasavo/parasaMhuo/parasaMuo/parasoMhiyoM
bihAna
bihAnO/bihAno/bihanau/bihanao/bihanaO/bihanavo/bihanavau
sabere
sabero/saberahoM/saberavo/saberahuz/sabarahiyoM/saberahuzoM
subaha
subahiyoM/subaho/subahoM/suBahao/subahavo
XIre
XIroM/XIrOM/XIrahoM/XIrahOM/XIrahiyo/XIrahiyoM
nIce
nIcoM/nIcOM/nIcahoM/nIcahOM/nIcahayo/nIcahiyoM
hamesA
hameso/hamesO/hamesayo/hamesayO
aso
asavahuz/asavo/asavahu/asavau/asovo/asovau
begahUz
begahuzvoM/begahuMvoM/begahuzvoz/begahuMvoz/begahuzoM/begahuMoM/begahuzoz/begahuMoz/begahuzvauM/begahuMvauM/begahuzvauz/begahuMvauz/begahuzauM/begahuMauM/begahuzauz/begahuMauz
anaxeKe
anaxeKalau/anaxeKalo/anaxeKalO
abahIz
abahuzyo/abahuMyo/abahuzo/abahuMo/abahuzvo/abahuMvo/abahuzyoM/abahuMyoz/abahizyo/abahiMyo/abahizo/abahiMo/abahizvo/abahiMvo/abahizyoz/abahiMyoM/abahizyoM/abahiMyoz
ahewu
ahewuvau/ahewuo/ahewuvo/ahewuau
beAbaru
beAbaruau/beAbaruo/beAbaruvo/beAbaruvau
awi
awiyo/awio/awiau/awiyau
kaBI
kaBiyau/kaBiau/kaBiyo/kaBio
jahAz
jahoz/jahoM/jahaOz/jahaOM/jahazu/jahaMu/jahaMoz/jahazoM/jahOz/jahOM
