Advrb_e
aba
abbE/abbai/abai/abahi/abahI/abahie/abahiye/abahe
kala
kalhE/kalai/kalahi/kalahI/kalahie/kalahiye
Aja
AjE/Ajai/Ajahi/AjahI/Ajahie/Ajahiye
parasoM
parasue/parasuye/parasoye/parasoe
bihAna
bihAnae/bihAnaye/bihAne/bihAnE/bihanai/bihanae
sabere
saberahi/saberahI/saberai/saberie/saberiye/saberIe/saberIye
subaha
subahai/subahie/subahiye
XIre
XIrahi/XIre/XIraheM/XIrahe
nIce
nIcoM/nIcE/nIcahe/nIcahE/nIcahaye/nIcahiyE
hamesA
hamese/hamesE/hamesaye/hamesayE
aso
asavai/asave/asavahi/asave/asove/asoye/asoe
begahUz
begahuzveM/begahuMveM/begahuzvez/begahuMvez/begahuzyeM/begahuMyeM/begahuzyez/begahuMyez
anaxeKe
anaxeKalai/anaxeKale
ahewu
ahewue/ahewuve/ahewuye
beAbarU
beAbarue/beAbaruve/beAbaruye
awi
awiye/awie/awiyai/awiai
kaBI
kaBiye/kaBie/kaBiyai
abahIz
abahizye/abahiMye/abahize/abahiMe/abahiMyai/abahizyai
jahAz
jahez/jaheM/jahEz/jahEM
