Gerund_ba_e1
KA
KAbau/KailoV/Kaibau
kara
karabau/kailoV/kayaloV
uTa
uTabau/uTaloV
ho
hobau/hoiloV
pI
piyabau/pIabau/pIyabau/pialoV/piyaloV/pIaloV/pIyaloV/pIbau
CU
Cuabau/Cubau/Cuvabau/CualoV/CuvaloV/CuyaloV/CUabau/CUbau/CUvabau/CUaloV/CUvaloV/CUyaloV
uTa
uTabau/uTaloV
so
soibau/soyabau/soyalau/soalau/soyaloV/soaloV/sobau
se
seibau/seyabau/seyalau/sealau/seyaloV/sealoV/sebau
xe
xebau
le
lebau
