Infinitive_yeke
KA
KAyeke/KAyake
KAyeke/KAyake
KAyeke/KAyake
KAyeke/KAyake
kara
kareke/karaike/karEke
kareke/karaike/karEke
kareke/karaike/karEke
kareke/karaike/karEke
le
leveke/levaike/lebEke
leveke/levaike/lebEke
leveke/levaike/lebEke
leveke/levaike/lebEke
ho
hoveke/hoyeke/hovaike/hovEke
hoveke/hoyeke/hovaike/hovEke
hoveke/hoyeke/hovaike/hovEke
hoveke/hoyeke/hovaike/hovEke
pI
piyaike/piyeke/pIyaike/pIyeke/piyEke
piyaike/piyeke/pIyaike/pIyeke/piyEke
piyaike/piyeke/pIyaike/pIyeke/piyEke
piyaike/piyeke/pIyaike/pIyeke/piyEke
CU
CUveke/CUyeke/CUvaike/Cuveke/Cuyeke/Cuvaike/CuvEke
CUveke/CUyeke/CUvaike/Cuveke/Cuyeke/Cuvaike/CuvEke
CUveke/CUyeke/CUvaike/Cuveke/Cuyeke/Cuvaike/CuvEke
CUveke/CUyeke/CUvaike/Cuveke/Cuyeke/Cuvaike/CuvEke
uTa
uTeke/uTaike/uTEke
uTeke/uTaike/uTEke
uTeke/uTaike/uTEke
uTeke/uTaike/uTEka
so
soveke/soyeke/sovaike/sovEke
soveke/soyeke/sovaike/sovEke
soveke/soyeke/sovaike/sovEke
soveke/soyeke/sovaike/sovEke
se
seveke/sevaike/sevEke
seveke/sevaike/sevEke
seveke/sevaike/sevEke
seveke/sevaike/sevEke
