Infinitive_yeke_e1
KA
Kaiyoke/Kaihoke/KaihukeV/KaihUkeV/Kahahuzke/KahahUzke/KAiyoke
kara
karayoke/kariyoke/karahoke/karihoke/karahuzke/karahUzke
uTa
uTaiyoke/uTiyoke/uTayoke/uTahoke/uTahuzke/uTahUzke
ho
hoiyoke/hoyoke/hovoke/hohukeV/hohUkeV/hohahuzke/hohahUzke
pI
piyoke/piboke/pibauke/pibahukeV/pibahUkeV/piahuzke/piahUzke/pIyoke/pIboke/pIbauke/pIbahukeV/pIbahUkeV/pIahuzke/pIahUzke
CU
Cuyahoke/Cuvahoke/Cuahoke/Cuyoke/Cuvoke/Cuoke/CuhukeV/CuhUkeV/Cuhahuzke/CuhahUzke/CUyahoke/CUvahoke/CUahoke/CUyoke/CUvoke/CUoke/CUhukeV/CUhUkeV/CUhahuzke/CUhahUzke
uTa
uTahoke/uTayoke/uTavoke/uTahukeV/uTahUkeV/uTahuzkeV/uTahUzkeV/uTahuke/uTahUke/uTahuzke/uTahUzke
so
soyoke/sooke/sovoke/sohoke/sohUkeV/sohukeV/sohahuzke/sohahUzke
se
seyoke/seoke/sevoke/sehoke/sehukeV/sehUkeV/sehahuzke/sehahUzke
le
leyoke
xe
xeyoke
