Infinitive_yeke_e
KA
KAhIMke/Kahazike/KahazhIke/Kaiyeke/KAiyeke
kara
karahIMke/kariyeke
uTa
uTahIMke/uTiyeke
ho
hohIMke/hohahIMke/hoiyeke
pI
piyahIMke/pIyahIMke/pIiyeke/piiyeke
CU
CuhahIMke/CuhIMke/CUhahIMke/CuhIMke/CUiyeke/Cuiyeke
so
soahIMke/sovahIMke/soiyeke
se
seahIMke/sevahIMke/seiyeke
le
leiyeke
xe
xeiyeke
