kara_e
KA
KAIke/Kahiyaike/Kaiyeke/KAiyeke
kara
kaiyeke/karIke/kaiVke/kariyeke
le
leiVke/lehike/leiyeke
ho
hoiyeke/hoiVke/hohiyeke
pI
piiVke/pihike/pihiyeke/pIiVke/pIhike/pIhiyeke/piiyeke/pIiyeke
CU
Cuiyeke/CuiVke/Cuhiyeke/CUiyeke/Cuiyeke
uTa
uTiyeke/uTiVke/uTahiVke/uTiyeke
so
soiyeke/sohiVke/soiVke
se
seiyeke/sehiVke/seiVke
