kara
KA
KAike/KAyake/KAke/Kaike/Kayake/KAika
kara
kaike/karike/karake/kayake/kaika
le
leike/leyake/leke/leika
ho
hoike/hoke/hoyake/hoika
pI
piike/pike/pIike/pIyake/piika/pIika
CU
Cuike/Cuke/CUike/CUke/CUyake/Cuyake/Cuika/CUika
uTa
uTake/uTike/uTika
so
soike/soke/soyake/soika
se
seike/seke/seyake/seika
