Noun_m_rednt_e
laikavA
laikave/laikavE/laikavai
laikavane/laikavanai/laikavanE
laikave/laikavE/laikavai
laikavane/laikavanai/laikavanE
rajavA
rajave/rajavai/rajavE
rajave/rajavai/rajavE
rajave/rajavai/rajavE
rajavanai/rajavanE/rajavane
GaravA
Garave/Garavai/GaravE
Garave/Garavai/GaravE
Garave/Garavai/GaravE
Garavanai/GaravanE/Garavane
KaracavA
Karacave/Karcavai/KaracavE
Karacave/Karcavai/KaracavE
Karacave/Karcavai/KaracavE
Karacavanai/Karacavane/KaracavanE
kaviyA
kaviye/kavie/kaviyai/kaviai
kaviye/kavie/kaviyai/kaviai
kaviye/kavie/kaviyai/kaviai
kaviyanai/kaviyane/kaviyanE
axamiyA
axamiye/axamie/axamiyai/axamiai/axamiyE
axamiye/axamie/axamiyai/axamiai/axamiyE
axamiye/axamie/axamiyai/axamiai/axamiyE
axamiyanai/axamiyanE/axamiyane
sawruvA
sawruve/sawruvai/sawruvE
sawruve/sawruvai/sawruvE
sawruve/sawruvai/sawruvE
sawruvanai/sawruvane/sawruvanE
aluvA
aluve/aluvai/aluvE
aluve/aluvai/aluvE
aluve/aluvai/aluvE
aluvanai/aluvanE/aluvane
kuvazvAz
kuvazveM/kuvazvez/kuvaMveM/kuvaMvez/kuvaMvai/kuvazvai/kuvaMvE/kuvazvE
kuvazveM/kuvazvez/kuvaMveM/kuvaMvez/kuvaMvai/kuvazvai/kuvaMvE/kuvazvE
kuvazveM/kuvazvez/kuvaMveM/kuvaMvez/kuvaMvai/kuvazvai/kuvaMvE/kuvazvE
kuvazne/kuvaznE/kuvaMne/kuvaMnE/kuvazvanai/kuvazvanE/kuazvane/kuazvanE/kuazvanai/kuaMvane/kuaMvanE/kuaMvanai
gehuzvAz
gehuzveM/gehuMveM/gehuzvez/gehuMvez/gehuzvai/gehuMvai/gehuzvE/gehuMvE
gehuzveM/gehuMveM/gehuzvez/gehuMvez/gehuzvai/gehuMvai/gehuzvE/gehuMvE
gehuzveM/gehuMveM/gehuzvez/gehuMvez/gehuzvai/gehuMvai/gehuzvE/gehuMvE
gehuzvanai/gehuMvanai/gehuMvane/gehuMvanE
sonaravA
sonarave/sonaravai/sonaravE
sonarave/sonaravai/sonaravE
sonarave/sonaravai/sonaravE
sonaravanai/sonaravane/sonaravanE
kroXavA
kroXave/kroXavai/kroXavE
kroXave/kroXavai/kroXavE
kroXave/kroXavai/kroXavE
kroXavanai/kroXavane/kroXavanE
