Noun_f_e1
laikI
laikio/laikiO/laikau
laikino/laikinO/laikinau
laikio/laikiO/laikau
laikino/laikinO/laikinau
mAI
mAio/mAiO/mAiau
mAino/mAinO/mAinau
mAio/mAiO/mAiau
mAino/mAinO/mAinau
rAwa
rAwo/rAwO/rAwau
rAwo/rAwO/rAwau
rAwo/rAwO/rAwau
rawano/rawanO/rawanau
rAwi
rawio/rawiO/rawiau
rawio/rawiO/rawiau
rawio/rawiO/rawiau
rawinao/rawinaO/rawinau
Orawa
Orawo/OrawO/Orawau
Orawanao/OrawanaO/Orawanau/Orawino
Orawo/OrawO/Orawau
Orawanao/OrawanaO/Orawanau/Orawino
BAsA
BAso/BAsO/BAsau
BAso/BAsO/BAsau
BAso/BAsO/BAsau
BAsano/BAsanO/BAsanau
gudZiyA
gudZiyo/gudZiyO/gudZiyau/gudZio/gudZiO/gudZiau
gudZiyo/gudZiyO/gudZiyau/gudZio/gudZiO/gudZiau
gudZiyo/gudZiyO/gudZiyau/gudZio/gudZiO/gudZiau
gudZiyano/gudZiyanO/gudZiyanau/gudZiano/gudZianO/gudZianau
sakwi
sakwio/sakwiO/sakwiau
sakwio/sakwiO/sakwiau
sakwio/sakwiO/sakwiau
sakwino/sakwinO/sakwinau
qwu
qwuo/qwuO/qwuau
qwuo/qwuO/qwuau
qwuo/qwuO/qwuau
qwuno/qwunO/qwunau
bahU
bahuo/bahuO/bahuau
bahuno/bahunO/bahunau
bahuo/bahuO/bahuau
bahuno/bahunO/bahunau
lO
lOvo/lOvO/lOau/lOvO/lOvau
lavano/lavanO/lavanau/lOano/lOanO/lOanau
lOvo/lOvO/lOvau/lOau
lavano/lavanO/lavanau/lOano/lOanO/lOanau
mAz
mAzo/mAzO/mAzau/mAMo/mAMO/mAMau
mAzano/mAzanO/mAzanau/mAMano/mAManO/mAManau
mAzo/mAzO/mAzau/mAMo/mAMO/mAMau
mAzano/mAzanO/mAzanau/mAMano/mAManO/mAManau
PotoM
PotoMo/PotoMO/PotoMau/Potozo/PotozO/Potozau
PotoMo/PotoMO/PotoMau/Potozo/PotozO/Potozau
PotoMo/PotoMO/PotoMau/Potozo/PotozO/Potozau
PotoMno/PotoMnO/PotoMnau/Ptozno/PotoznO/Potoznau
BUiM
BUiMo/BUiMO/BUiMau/BUizo/BUizO/BUizau
BUiMano/BUiManO/BUiManau/BUizano/BUizanO/BUizanau
BUiMo/BUiMO/BUiMau/BUizo/BUizO/BUizau
BUiMano/BUiManO/BUiManau/BUizano/BUizanO/BUizanau
BOM
BOMo/BOMO/BOMau/BOzo/BOzO/BOzau
BOMano/BOManO/BOManau/BOzano/BOzanO/BOzanau
BOMo/BOMO/BOMau/BOzo/BOzO/BOzau
BOMano/BOManO/BOManau/BOzano/BOzanO/BOzanau
BarasAIM
BarasaiMo/BarasaiMO/BarasaiMau/Barasaizo/BarasaizEO/Barasaizau
BarasaiMno/BarasaiMnO/BarasaiMnau/Barasaizno/BarasaiznO/Barasaiznau
BarasaiMo/BarasaiMO/BarasaiMau/Barasaizo/BarasaizEO/Barasaizau
BarasaiMno/BarasaiMnO/BarasaiMnau/Barasaizno/BarasaiznO/Barasaiznau
Bora
Boro/BorO/Borau
Boro/BorO/Borau
Boro/BorO/Borau
Borano/BoranO/Boranau
Poto
PotoO/Potoau
PotoO/Potoau
PotoO/Potoau
Potono/PotonO/Potonau
