Noun_f_rednt_e
laikiyA
laikiye/laikiyai/laikiyE
laikiyanai/laikianai/laikiyane/laikiane/laikiyanE/laikianE
laikiye/laikiyai/laikiyE
laikiyanai/laikianai/laikiyane/laikiane/laikiyanE/laikianE
maiyA
maiye/maiyai/maiyE
maiyanai/maianai/maiyanE/maianE/maiyane/maiane
maiye/maiyai/maiyE
maiyanai/maianai/maiyanE/maianE/maiyane/maiane
rawiyA
rawiye/rawiyai/rawiyE
rawiye/rawiyai/rawiyE
rawiye/rawiyai/rawiyE
rawiyanai/rawiyane/rawiyanE
OrawiyA
Orawiye/Orawiyai/OrawiyE
Orawiyanai/Orawianai/Orawiyane/Orawiane/OrawiyanE/OrawianE
Orawiye/Orawiyai/OrawiyE
Orawiyanai/Orawianai/Orawiyane/Orawiane/OrawiyanE/OrawianE
BasavA
Basave/Basavai/BasavE
Basave/Basavai/BasavE
Basave/Basavai/BasavE
Basavanai/Basavane/BasavanE
gudZiyavA
gudZiyave/gudZiyavE/gudZiavai/gudZiavE/gudZyavai/gudZiavae
gudZiyave/gudZiyavE/gudZiavai/gudZiavE/gudZyavai/gudZiavae
gudZiyave/gudZiyavE/gudZiavai/gudZiavE/gudZyavai/gudZiavae
gudZiyavanai/gudZiyavanE/gudZiyavane
sakwiyA
sakwiye/sakwiyai/sakwiyE
sakwiye/sakwiyai/sakwiyE
sakwiye/sakwiyai/sakwiyE
sakwiyanai/sakwiyane/sakwiyanE/sakwianai/sakwiane/sakwianE
qwuvA
qwuve/qwuvai/qwuvE/qwuae/qwuaE
qwuve/qwuvai/qwuvE/qwuae/qwuaE
qwuve/qwuvai/qwuvE/qwuae/qwuaE
qwuvanai/qwuvane/qwuvanE/qwuanai/qwuane/qwuanE
bahuvA
bahuve/bahuvai/bahuvE
bahuve/bahuvai/bahuvE
bahuve/bahuvai/bahuvE
bahuvanai/bahuvane/bahuvanE/bahuanai/bahuane/bahuanE
lauvA
lauve/lauvai/lauvE
lauvanai/lauvane/lauvanE/lauanai/lauane/lauanE
lauve/lauvai/lauvE
lauvanai/lauvane/lauvanE/lauanai/lauane/lauanE
BoravA
Borave/Boravai/BoravE
Borave/Boravai/BoravE
Borave/Boravai/BoravE
Boravanai/Boravane/BoravanE
PotauvA
Potauve/Potauvai/PotauvE
Potauve/Potauvai/PotauvE
Potauve/Potauvai/PotauvE
Potauvane/Potauvanai/PotauvanE
PotoMvA
PotoMve/Potozvai/PotoMvE/Potozve/PotozvE/Potozvai
PotoMve/Potozvai/PotoMvE/Potozve/PotozvE/Potozvai
PotoMve/Potozvai/PotoMvE/Potozve/PotozvE/Potozvai
PotoMvane/Potozvane/PotoMvanai/Potozvanai/PotoMvanaE/PotozvanaE
BUiMvA
BUiMve/BUizve/BUiMvai/BUizvai/BUiMvE/BUizvE
BUiMvane/BUizvane/BUIManai/BUIzanai/BUiMvanai/BUizvanai/BUIManae/BUIzanae/BUiMvanE/BUizvanE/BUIManE/BUIzanE
BUiMve/BUizve/BUiMvai/BUizvai/BUiMvE/BUizvE
BUiMvane/BUizvane/BUIManai/BUIzanai/BUiMvanai/BUizvanai/BUIManae/BUIzanae/BUiMvanE/BUizvanE/BUIManE/BUIzanE
BOMvA
BOMve/BOzve/BOMvai/BOzvai/BOMvE/BOzvE
BOMvane/BOzvane/Bazuane/BaMuvane/BOMvanai/BOzvanai/Bazuanai/BaMuvanai/BOMvanE/BOzvanE/BazuanE/BaMuvanE
BOMve/BOzve/BOMvai/BOzvai/BOMvE/BOzvAE
BOMvane/BOzvane/Bazuane/BaMuvane/BOMvanai/BOzvanai/Bazuanai/BaMuvanai/BOMvanE/BOzvanE/BazuanE/BaMuvanE
BarasaiMyA
BarasaiMye/Barasaizye/BarasaiMyE/BarasaizyE/BarasaiMyai/Barasaizyai
BarasaiMye/Barasaizye/BarasaiMyE/BarasaizyE/BarasaiMyai/Barasaizyai
BarasaiMye/Barasaizye/BarasaiMyE/BarasaizyE/BarasaiMyai/Barasaizyai
BarasaiMyane/Barasaizyane/BarasaiMyanai/Barasaizyanai/BarasaiMyanE/BarasaizyanE
