Noun_m_e1
laikA
laiko/laikO/laikau
laikano/laikanO/laikanau
laiko/laikO/laikau
laikanO/laikano/laikanau
rAjA
rAjo/rAjO/rAjau
rAjo/rAjO/rAjau
rAjo/rAjO/rAjau
rAjano/rAjanO/rAjanau/rajano/rajanO/rajanau
Gara
Garo/GarO/Garau
Garo/GarO/Garau
Garo/GarO/Garau
Garano/GaranO/Garanau
Karca
Karco/KarcO/Karcau
Karco/KarcO/Karcau
Karco/KarcO/Karcau
Karcano/KarcanO/Karcanau
kavi
kavio/kaviO/kaviau
kavio/kaviO/kaviau
kavio/kaviO/kaviau
kavino/kavinO/kavinau
AxamI
Axamio/AxamiO/Axamiau
Axamio/AxamiO/Axamiau
Axamio/AxamiO/Axamiau
Axamino/AxaminO/Axaminau
sonarA
sonaro/sonarO/sonarau
sonaro/sonarO/sonarau
sonaro/sonarO/sonarau
sonarano/sonaranO/sonaranau
sawru
sawruo/sawruO/sawruau
sawruo/sawruO/sawruau
sawruo/sawruO/sawruau
sawruano/sawruanO/sawrunaau
AlU
Aluo/AluO/Aluau
Aluo/AluO/Aluau
Aluo/AluO/Aluau
Aluno/AlunO/Alunau
kuvAz
kuvoM/kuvOz/kuoM/kuOz/kuauM/kuvauM/kuvauz/kuauz/kuvoz/kuvOM/kuOM/kuoz
kuvoM/kuvOz/kuoM/kuOz/kuauM/kuvauM/kuvauz/kuauz/kuvoz/kuvOM/kuOM/kuoz
kuvoM/kuvOz/kuoM/kuOz/kuauM/kuvauM/kuvauz/kuauz/kuvoz/kuvOM/kuOM/kuoz
kuMvano/kuMvanO/kuMano/kuaMnO/kuvanauz/kuaznau/kuvaMno/kuvaMnau/kuaznau/kuvazno/kuvaznO/kuazno/kuaznO/kuvaznau/kuaMnau
gehUz
gehuzo/gehuzO/gehuzau/gehuMo/gehuMO/gehuMau
gehuzo/gehuzO/gehuzau/gehuMo/gehuMO/gehuMau
gehuzo/gehuzO/gehuzau/gehuMo/gehuMO/gehuMau
gehuzno/gehuznO/gehuznau/gehuMno/gehuMnO/gehuMnau
kroXa
kroXo/kroXO/kroXau
kroXo/kroXO/kroXau
kroXo/kroXO/kroXau
kroXo/kroXO/kroXau
lakaTo
lakaToau/lakaToo/lakaToO
lakaTano/lakaTanO/lakaTanau/lakaTono/lakaTonO/lakaTonau
lakaToau/lakaToo/lakatoO
lakaTano/lakaTanO/lakaTanau/lakaTono/lakaTonO/lakaTonau
sarasoz
sarasoMau/sarasozau
sarasoMno/sarasoMnO/sarasoMnau/sarasozno/sarasoznO/sarasoznau/sarasaMno/sarasaMnO/sarasaMnau/sarasazano/sarasazanO/sarasaznau
sarasoMau/sarasozau
sarasoMno/sarasoMnO/sarasoMnau/sarasozno/sarasoznO/sarasoznau/sarasaMno/sarasaMnO/sarasaMnau/sarasazano/sarasazanO/sarasaznau
gosAIM
gosaiMo/gosaiMO/gosaiMau/gosaizo/gosaizO/gosaizau
gosaiMo/gosaiMO/gosaiMau/gosaizo/gosaizO/gosaizau
gosaiMo/gosaiMO/gosaiMau/gosaizo/gosaizO/gosaizau
gosaiMno/gosaiMnO/gosaiMnau/gosaizno/gosaiznO/gosaiznau
