Noun_m_e
laikA
laike/laikai/laikE
laikane/laikanE/laikanai
laike/laikai/laikE
laikane/laikanE/laikanai
rAjA
rAje/rAjE/rAjai
rAje/rAjE/rAjai
rAje/rAjE/rAjai
rajanai/rajane/rajanE/rAjanai/rAjane/rAjanE
Gara
Gare/GarE/Garai
Gare/GarE/Garai
Gare/GarE/Garai
Garanai/Garane/GaranE
Karca
Karce/Karcai/KarcE
Karce/Karcai/KarcE
Karce/Karcai/KarcE
Karcanai/Karcane/KarcanE
kavi
kavie/kaviE
kavie/kaviE
kavie/kaviE
kavine/kavinE
AxamI
Axamie/AxamiE
Axamie/AxamiE
Axamie/AxamiE
Axamine/AxaminE
sonarA
sonare/sonarai/sonarE
sonare/sonarai/sonarE
sonare/sonarai/sonarE
sonaranai/sonarane/sonaranE
sawru
sawrue/sawruE/sawruai
sawrue/sawruE/sawruai
sawrue/sawruE/sawruai
sawrune/sawrunE/sawrunai/sawrunaI
AlU
Alue/AluE
Alue/AluE
Alue/AluE
Alune/AlunE
kuvAz
kuveM/kueM/kuvez/kuez/kuvzai/kuvEM/kuvMai/kuvEz
kuveM/kueM/kuvez/kuez/kuvzai/kuvEM/kuvMai/kuvEz
kuveM/kueM/kuvez/kuez/kuvzai/kuvEM/kuvMai/kuvEz
kuvaznai/kuvaMnai/kuvazne/kuvaMne/kuvaznE/kuvaMnE
gehUz
gehuze/gehuzE/gehuMe/gehuME
gehuze/gehuzE/gehuMe/gehuME
gehuze/gehuzE/gehuMe/gehuME
gehuzne/gehuznE/gehuMne/gehuMnE
kroXa
kroXe/kroXE/kroXai
kroXe/kroXE/kroXai
kroXe/kroXE/kroXai
kroXe/kroXE/kroXai
lakaTo
lakaToe/lakaToE/lakaToaI
lakaTone/lakaTonE/lakaTonai/lakaTane/lakaTanE/lakaTanai
lakaToe/lakaToE/lakaToaI
lakaTone/lakaTonE/lakaTonai/lakaTane/lakaTanE/lakaTanai
sarasoz
sarasoMe/sarasoME/sarasoMai/sarasoze/sarasozE/sarasozai
sarasoMne/sarasoMnE/sarasoMnai/sarasozne/sarasoznE/sarasoznai/sarasaMne/sarasaMnE/sarasaMnai/sarasazne/sarasaznE/sarasaznai
sarasoMe/sarasoME/sarasoMai/sarasoze/sarasozE/sarasozai
sarasoMne/sarasoMnE/sarasoMnai/sarasozne/sarasoznE/sarasoznai/sarasaMne/sarasaMnE/sarasaMnai/sarasazne/sarasaznE/sarasaznai
gosAIM
gosaiMe/gosaiME/gosaize/gosaizE
gosaiMe/gosaiME/gosaize/gosaizE
gosaiMe/gosaiME/gosaize/gosaizE
gosaiMne/gosaiMnE/gosaiMnai/gosaizne/gosaiznE/gosaiznai
