Noun_f_e
laikI
laikie/laikiE/laikai
laikine/laikinE/laikinai
laikie/laikiE/laikai
laikine/laikinE/laikinai
mAI
mAie/mAiai/mAiE
mAine/mAinE/mAinai
mAie/mAiai/mAiE
mAine/mAinE/mAinai
rAwa
rAwe/rAwai/rAwE
rAwe/rAwai/rAwE
rAwe/rAwai/rAwE
rawanai/rawane/rawanE
rAwi
rawie/rawiE/rawiai
rawie/rawiE/rawiai
rawie/rawiE/rawiai
rawinae/rawinaE/rawinai
Orawa
Orawe/OrawE/Orawai
Orawane/OrawanE/Orawanai/Orawine
Orawe/OrawE/Orawai
Orawane/OrawanE/Orawanai/Orawine
BAsA
BAse/BAsai/BAsE
BAse/BAsai/BAsE
BAse/BAsai/BAsE
BAsanai/BAsane/BAsanE
gudZiyA
gudZiye/gudZie/gudZiyai/gudZiE/gudZiyE/gudZiai
gudZiye/gudZie/gudZiyai/gudZiE/gudZiyE/gudZiai
gudZiye/gudZie/gudZiyai/gudZiE/gudZiyE/gudZiai
gudZiyanai/gudZiyane/gudZiyanE/gudZianai/gudZiane/gudZianE
sakwi
sakwie/sakwiE/sakwiai
sakwie/sakwiE/sakwiai
sakwie/sakwiE/sakwiai
sakwine/sakwinE/sakwinai
qwu
qwue/qwuE/qwuai
qwue/qwuE/qwuai
qwue/qwuE/qwuai
qwunai/qwune/qwunE
bahU
bahue/bahuE/bahuai
bahune/bahunE/bahunai
bahue/bahuE/bahuai
bahune/bahunE/bahunai
lO
lOve/lOe/lOvai/lOvE/lOE/lOai
lOvanai/lOvane/lOvanE/lOanai/lOane/lOanE
lOve/lOe/lOvai/lOvE/lOE/lOai
lOvanai/lOvane/lOvanE/lOanai/lOane/lOanE
mAz
mAze/mAzE/mAzai/mAMe/mAME/mAMai
mAzane/mAzanE/mAzanai/mAMane/mAManE/mAManai
mAze/mAzE/mAzai/mAMe/mAME/mAMai
mAzane/mAzanE/mAzanai/mAMane/mAManE/mAManai
PotoM
PotoMe/PotoE/PotoMai/Potoze/PotozE/Potozai
PotoMe/PotoE/PotoMai/Potoze/PotozE/Potozai
PotoMe/PotoE/PotoMai/Potoze/PotozE/Potozai
PotoMne/PotoMnE/PotoMnai/Ptozne/PotoznE/Potoznai
BUiM
BUiMe/BUiME/BUiMai/BUize/BUizE/BUizai
BUiMane/BUiManE/BUiManai/BUizane/BUizanE/BUizanai
BUiMe/BUiME/BUiMai/BUize/BUizE/BUizai
BUiMane/BUiManE/BUiManai/BUizane/BUizanE/BUizanai
BOM
BOMe/BOME/BOMai/BOze/BOzE/BOzai
BOMane/BOManE/BOManai/BOzane/BOzanE/BOzanai
BOMe/BOME/BOMai/BOze/BOzE/BOzai
BOMane/BOManE/BOManai/BOzane/BOzanE/BOzanai
BarasAIM
BarasaiMe/BarasaiME/BarasaiMai/Barasaize/BarasaizE/Barasaizai
BarasaiMne/BarasaiMnE/BarasaiMnai/Barasaizne/BarasaiznE/Barasaiznai
BarasaiMe/BarasaiME/BarasaiMai/Barasaize/BarasaizE/Barasaizai
BarasaiMne/BarasaiMnE/BarasaiMnai/Barasaizne/BarasaiznE/Barasaiznai
Bora
Bore/Borai/BorE
Bore/Borai/BorE
Bore/Borai/BorE
Boranai/Borane/BoranE
Poto
Potoe/PotoE/Potoai
Potoe/PotoE/Potoai
Potoe/PotoE/Potoai
Potone/PotonE/Potonai
