Pres_Prtcpl_rdp_wai1
KA
KAwai/Kaiwai/KAwE/KEwe/KAiwa
pI
piyawai/piawai/piawe/piyawe/piawE/piyawE/pIyawai/pIawai/pIawe/pIyawe/pIawE/pIyawE/piiwa
uTa
uTawai/uTewai/uTawE/uTewE/uTiwa
kara
karawai/karawE/kariwa
CU
Cuawai/Cuvawai/CUawai/CUvawai/CuawE/CuvawE/CUawE/CUvawE/CUiwa
ho
howai/hoawai/hovawai/howE/hoawE/hovawE/hoiwa
le
lewai/levawai/lewE/levawE/leiwa
xe
xewai/xevawai/xewE/xevawE/xeiwa
se
seawai/sevawai/sewE/seawE/sevawE/seiwa
so
soawai/sovawai/sowE/soawE/sovawE/soiwa
