Pres_Prtcpl_e_wa1
KA
KAiwe/Kaiwai/KAwE
pI
piyawai/piawai/piawe/piyawe/piawE/piyawE/pIyawai/pIawai/pIawe/pIyawe/pIawE/pIyawE
uTa
uTawai/uTewai/uTawE/uTewE
kara
karawai/karawE/kariwe
CU
Cuawai/Cuvawai/CUawai/CUvawai/CuawE/CuvawE/CUawE/CUvawE
ho
howai/hoawai/hovawai/howE/hoawE/hovawE
le
lewai/levawai/lewE/levawE
xe
xewai/xevawai/xewE/xevawE
se
seawai/sevawai/sewE/seawE/sevawE
so
soawai/sovawai/sowE/soawE/sovawE
