PstPerf_Plus_Aux_e1_yale
KA
Kailehi/Kayaliyau/Kaliyau/Kailiyau/KAyalahU/kAlahU/KAiyo
kara
kayalehi/karayaliyau/kayaliyau/karaliyau/karailiyau/karayalahU/karalahU/kariyo
le
lelahiye/leyaliyau/leliyau/leiliyau/leyalahU/lelahU/leiyo
xe
xelahiye/xeyaliyau/xeliyau/xeiliyau/xeyalahU/xelahU/xeiyo
ho
holayahi/hoyaliyau/holiyau/hoiliyau/hoyalahU/holahU/hoiyo
CU
CUlayahi/CUyaliyau/CUliyau/CUiliyau/CUyalahU/CUlahU/CUiyo
uTa
uTalayahi/uTayaliyau/uTaliyau/uTailiyau/uTayalahU/uTalahU/uTiyo
pI
piyalayahi/pIyalayahi/pIyaliyau/pIliyau/pIiliyau/pIyalahU/pIlahU/pIiyo/piiyo
se
seyalahi/seyaliyau/seliyau/seiliyau/seyalahU/selahU/seiyo
so
sovalahi/soyaliyau/soliyau/soiliyau/soyalahU/solahU/soiyo
