PstPerf_Plus_Aux_yale
KA
Kayale/Kaile/KAila/KayalI/KailiV/KayaliV
kara
kaile/kayale/karailiV/kailiV/kayaliV
le
leli/leali/leyali/lealI/leyalI/leiliV/leyaliV
xe
xeli/xeali/xeyali/xealI/xeyalI/xeiliV/xeyaliV
ho
holi/hoali/hoyali/hoalI/hoyalI/hoiliV/hoyaliV
CU
CUli/CUali/CUyali/CUalI/CUyalI/CUiliV/CUyaliV
uTa
uTali/uTalI/uTailiV/uTayaliV
pI
pilI/pili/piali/piyali/pialI/piyalI/pIiliV/piiliV/pIyaliV/piyaliV
se
seyali/seyalI/seali/sealI/seiliV/seyaliV
so
soli/solI/soali/soalI/soyali/soyalI/soiliV/soyaliV
