PstPerf_Plus_Aux_e_yale
KA
Kailae/KailaE/Kayalae/KayalaE/Kayaliye/Kailiyai/KAiye
kara
kailae/kailaE/kayalae/kayalaE/karaliye/karailiyai/kailiyai/kaiye/kariye
le
leliyae/leliyaE/leliie/leliiE/leiye
xe
xeliie/xeliiE/xeliyae/xeliyaE/xeiye
ho
holiie/holiiE/holiyae/holiyaE/hoiye
CU
CUliie/CUliiE/CUliyae/CUliyaE/CUiye
uTa
uTaliie/uTaliiE/uTaliyae/uTaliyaE/uTaliye/uTiliyai/uTaliyai/uTaiye
pI
piyaliie/piyaliiE/piyaliyae/piyaliyaE/pialiie/pialiiE/pialiyae/pialiyaE/piiye/pIiye
se
sealie/sealiE/sealiyai/sealiyaI/seiye
so
sovalie/sovaliE/sovaliyai/sovaliyaI/soiye
