PstPerf_Minus_Aux_ila
KA
Kaili/KailI
Kaili/KailI
Kaile/Kayali/KailI
KailIM/KailiM
Kailai/Kayalai/Kayalakai/KayalakE/KAlaKina/KalaKina
Kailana/Kayalakai/KayalakE/KAlaKina/KalaKina
Kaili/KailI
Kaili/KailI
Kaile/Kayali/KailI
KailIM/KailiM
Kailai/Kayalai
Kailana
kara
karaliyE
karali
karali
karali
karalE/karalakai/karalakE/kailiyai/kailayai/kailaKina/karalaKina
karalE/karalakai/karalakE/kailiyai/kailayai/kailaKina/karalaKina
karaliyE
karali
karali
karali
karalE
kailana/kailaWina
le
leli/lelI
leli/lelI
leli/lelI
lehali
lelakE/lelakai/lelaKina
lelakE/lelakai/lelaKina
leli/lelI
leli/lelI
leli/lelI
lehali
lelakE
lelaWina
ho
holi/hoila/holai
holi/hoila/holai
holE/hoila/holai
holE/hoila/holai
holE/hoila/holai/holalakai/holalakE/holaKina/hoilaKina
holE/hoila/holai/holalakai/holalakE/holaKina/hoilaKina
holi/hoila/holai
holi/hoila/holai
holE/hoila/holai
holE/hoila/holai
holE/hoila/holai
holaWina/hoilina/holina
CU
Cuali/Cuvali/CualI/CuvalI/CUali/CUvali/CUalI/CUvalI
Cuali/Cuvali/CualI/CuvalI/CUali/CUvali/CUalI/CUvalI
Cuali/Cuvali/CualI/CuvalI/CUali/CUvali/CUalI/CUvalI
Cuali/Cuvali/CualI/CuvalI/CUali/CUvali/CUalI/CUvalI
Cuali/Cuvali/CualI/CuvalI/CUali/CUvali/CUalI/CUvalI/Culakai/CulakE/Cuvalakai/CUlaKina/CUilaKina
Cuali/Cuvali/CualI/CuvalI/CUali/CUvali/CUalI/CUvalI/Culakai/CulakE/Cuvalakai/CUlaKina/CUilaKina
Cuali/Cuvali/CualI/CuvalI/CUali/CUvali/CUalI/CUvalI
Cuali/Cuvali/CualI/CuvalI/CUali/CUvali/CUalI/CUvalI
Cuali/Cuvali/CualI/CuvalI/CUali/CUvali/CUalI/CUvalI
Cuali/Cuvali/CualI/CuvalI/CUali/CUvali/CUalI/CUvalI
Cuali/Cuvali/CualI/CuvalI/CUali/CUvali/CUalI/CUvalI
CualaWina
uTa
uTali/uTalI
uTali/uTalI
uTali/uTalI
uTali/uTalI
uTala/uTalakai/uTalakE/uTalayai/uTalai/uTalO/uTalaKina
uTali/uTalI/uTalakai/uTalakE/uTalayai/uTalai/uTalO/uTalaKina
uTali/uTalI
uTali/uTalI
uTali/uTalI
uTali/uTalI
uTala
uTalaWina
pI
piyale
piyale
piyale
piyale
piyale/piyalakai/piyalakE/pilaKina
piyale/piyalakai/piyalakE/pilaKina
piyale
piyale
piyale
piyale
piyale
piyalaWina
se
seili/seilI/seyali/seyalI/seali/sealI
seili/seilI/seyali/seyalI/seali/sealI
seyale
seyale
seyale/seyalakai/seyalakE/selaKina
seyale/seyalakai/seyalakE/selaKina
seili/seilI/seyali/seyalI/seali/sealI
seili/seilI/seyali/seyalI/seali/sealI
seili/seilI/seyali/seyalI/seali/sealI
seyale
seyale
seyalaWina
so
soili/soilI/soyali/soyalI/soali/soalI
soili/soilI/soyali/soyalI/soali/soalI
soyale/soile
soyale/soile
soyale/soile/sovalakai/sovalakE/solaKina
soyale/soile/sovalakai/sovalakE/solaKina
soili/soilI/soyali/soyalI/soali/soalI
soili/soilI/soyali/soyalI/soali/soalI
soile/soyale
soile/soyale
soile/soyale
sovalaWina/soyalaWina
xe
xeli/xelI
xeli/xela
xele/xehale
xele/xehale
xele/xehale/xelakai/xelakE/xelalakai/xelaKina
xele/xehale/xelakai/xelakE/xelalakai/xelaKina
xele/xehale
xele/xehale
xele/xehale
xele/xehale
xele/xehale
xelaWina
