RaRTI_a_e
u
okarai/ohike/ohIke/okarE
okarai/ohike/ohIke/okarE
okarai/ohike/ohIke/okarE
okarai/ohike/ohIke/okarE
okarai/ohike/ohIke/okarE
okarai/ohikeá/ohIke/okarE
okarai/ohike/ohIke/okarE
okarai/ohike/ohIke/okarE
onakarai/unakarai/onahIke/onhIkeá/onakarE
onakarai/unakarai/onahIke/onhIkeá/onakarE
onakarai/unakarai/onahIke/onhIke/onakarE
onakarai/unakarai/onahIke/onhIke/onakarE
onakarai/unakarai/onahIke/onhIke/onakarE
onakarai/unakarai/onahIkeá/onhIke/onakarE
onakarai/unakarai/onahIke/onhIke/onakarE
onakarai/unakarai/onahIke/onhIke/onakarE
je
jekarai/jekare
jekarai/jekare
jekarai/jekare
jekarai/jekare
jekarai/jekare
jekarai/jekare
jekarai/jekare
jekarai/jekare
jenakarai/jinakarai/jenahike/jenahIke/jenhike/jenhIke/jenakarE
jenakarai/jinakarai/jenahike/jenahIke/jenhike/jenhIke/jenakarE
jenakarai/jinakarai/jenahike/jenahIke/jenhike/jenhIke/jenakarE
jenakarai/jinakarai/jenahike/jenahIke/jenhike/jenhIke/jenakarE
jenakarai/jinakarai/jenahike/jenahIke/jenhike/jenhIke/jenakarE
jenakarai/jinakarai/jenahike/jenahIke/jenhike/jenhIke/jenakarE
jenakarai/jinakarai/jenahika/jenahIke/jenhike/jenhIke/jenakarE
jenakarai/jinakarai/jenahike/jenahIke/jenhike/jenhIke/jenakarE
kavana
kekarai/kehuke/kehUke/kekarE/kekaro
kekarai/kehukeá/kehUka/kekarE/kekaro
kekarai/kehukeá/kehUke/kekarE/kekaro
kekarai/kehuke/kehUke/kekarE/kekaro
kekarai/kehuka/kehUka/kekarE/kekaro
kekarai/kehuke/kehUke/kekarE/kekaro
kekarai/kehuke/kehUke/kekarE/kekaro
kekarai/kehuke/kehUke/kekarE/kekaro
kinakarai/kenakarai/kenahuke/kenahUke/kenakarE/kenhuke/kenhUke
kinakarai/kenakarai/kenahuke/kenahUke/kenakarE/kenhuke/kenhUke
kinakarai/kenakarai/kenahuke/kenahUke/kenakarE/kenhuke/kenhUke
kinakarai/kenakarai/kenahuke/kenahUke/kenakarE/kenhuke/kenhUke
kinakarai/kenakarai/kenahuke/kenahUke/kenakarE/kenhuke/kenhUke
kinakarai/kenakarai/kenahuke/kenahUke/kenakarE/kenhuke/kenhUke
kinakarai/kenakarai/kenahuke/kenahUke/kenakarE/kenhuke/kenhUke
kinakarai/kenakerai/kenahuke/kenahUke/kenakarE/kenhuke/kenhUke
i
yekarai/ekarai/yehike/yehIke
yekarai/ekarai/yehike/yehIke
yekarai/ekarai/yehike/yehIke
yekarai/ekarai/yehike/yehIke
yekarai/ekarai/yehike/yehIke
yekarai/ekarai/yehike/yehIke
yekarai/ekarai/yehike/yehIke
yekarai/ekarai/yehike/yehIke
inakarai/yenakarai/enakarai/yenahika/yenahIka/yenhike/yenhIke
inakarai/yenakarai/enakarai/yenahike/yenahIke/yenhike/yenhIke
inakarai/yenakarai/enakarai/yenahike/yenahIke/yenhike/yenhIke
inakarai/yenakarai/enakarai/yenahike/yenahIke/yenhike/yenhIke
inakarai/yenakarai/enakarai/yenahika/yenahIke/yenhike/yenhIke
inakarai/yenakarai/enakarai/yenahike/yenahIke/yenhike/yenhIke
inakarai/yenakarai/enakarai/yenahike/yenahIke/yenhike/yenhIke
inakarai/yenakarai/enakarai/yenahike/yenahIke/yenhike/yenhIke
saba
-
-
-
-
-
-
-
-
sabakarai/sabahike/sabahIke/saBahike/saBahIke
sabakarai/sabahike/sabahIke/saBahike/saBahIke
sabakarai/sabahike/sabahIke/saBahike/saBahIke
sabakarai/sabahike/sabahIke/saBahike/saBahIke
sabakarai/sabahike/sabahIke/saBahike/saBahIke
sabakarai/sabahika/sabahIke/saBahike/saBahIke
sabakarai/sabahike/sabahIke/saBahike/saBahIke
sabakarai/sabahike/sabahIke/saBahike/saBahIke
