subj
KA
KAiM/KAiz
KailaV
KAiM/KAiz/KAzya
KAhi
KAiM/KAiz
KA
KAiM/KAiz
KAzya
-
-
KAiM/KAiz/KAzya
-
kara
kariM/karIM/kariz/karIz
kailAV/kayalAV
kariM/karIM/kariz/karIz/karEM
karai
kariM/karIM/kariz/karIz
karaV
kariM/karIM/kariz/karIz/karEM
karEM
-
-
kariM/karIM/kariz/karIz/karEM
-
le
lI/li/leiM/leiz/lehiM/lehIM/leho
lela/lele
leiM/leiz/lehiM/lehIM
lelakE/lelako
leiM/leiz/lehiM/lehIM/lebo
lAV
leiM/leiz/lehiM/lehIM/leMi
leMi/laMi/lazi
-
-
leiM/leiz/lehiM/lehIM/leMi/laMi/lazi/leho
-
ho
hoiM/hoiz
holaV
hovaiM/hoMi/hohuM/hovaho
hoya
hoiM/hoiz
hova
hovaiM/hoMi
hoveM/hovez/hoMve/hozve
-
-
hoveM/hovez/hoMve/hozva/hoMya/hozya
-
pI
pihiM/pihIM
piyalaV/pIyalaV
piiM/piiz/pihiM/pihIM/piyaz/pIyaz/piyaM/pIyaM
piyai
piiM/piiz/pihiM/pihIM
piyaV/pia
piiM/piiz/pihiM/pihIM/piyaz/pIyaz/piyaM/pIyaM
piiM/piiz/pihiM/pihIM
-
-
piiM/piiz/pihiM/pIhIM/pIMi/pIzi
-
CU
CUiM/CUiz/CUhiM/CuhIM/CuiM/Cuiz
CUalaV/CualaV
CUiM/CUiz/CUhiM/CUhIM/CUyaz/Cuyaz/CUyaM/CuyaM/CUaiM/CUaiz/CUahiM/CUahIM/CUayaz/Cuayaz/CUayaM/CuayaM/CUvaiM/CUvaiz/CUvahiM/CUvahIM/CUvayaz/Cuvayaz/CUvayaM/CuvayaM
CUvai/Cuvai/CUai/Cuai
CUiM/CUiz/CUhiM/CUhIM/CuiM/CuhiM/CuhIM
CUvaV/CUvA/Cua/CUa
CUiM/CUiz/CUhiM/CUhIM/CUyaz/Cuyaz/CUyaM/CuyaM/CUaiM/CUaiz/CUahiM/CUahIM/CUayaz/Cuayaz/CUayaM/CuayaM/CUvaiM/CUvaiz/CUvahiM/CUvahIM/CUvayaz/Cuvayaz/CUvayaM/CuvayaM
CUveM/CuveM/CUvez/Cuvez
-
-
CUiM/CUiz/CUhiM/CUhIM/CUyaz/Cuyaz/CUyaM/CuyaM/CUaiM/CUaiz/CUahiM/CUahIM/CUayaz/Cuayaz/CUayaM/CuayaM/CUvaiM/CUvaiz/CUvahiM/CUvahIM/CUvayaz/Cuvayaz/CUvayaM/CuvayaM
-
uTa
uTIM/uTiM/uTIz/uTiz
uTalaV
uTIM/uTiM/uTIz/uTiz/uTEM/uTaiz/uTaiM
uTai/uTE
uTIM/uTiM/uTIz/uTiz
uTaV/uTa/uTA
uTaiM/uTEM
uTaiM/uTaiz/uTEM
-
-
uTaiM/uTaiz/uTEM
-
so
soiM/soiz
sovaV/soaV
soiM/soiz
sovai/sovE
soiM/soiz
soaV/sovaV
soiM/soiz/sovaiz/sovaiM
soiM/soiz/sovaiz/sovaiM
-
-
soiM/soiz/sovaiz/sovaiM
-
se
seiM/seiz
sevaV/seaV
seiM/seiz
sevai/sevE
seiM/seiz
seaV/sevaV
seiM/seiz/sevaiz/sevaiM
seiM/seiz/sevaiz/sevaiM
-
-
seiM/seiz/sevaiz/sevaiM
-
