Adj_case_e
aneka
aneke
aneke
kai
kaweke/kawekahiz/kaiye/kawekahi
kaweke/kawekahiz/kaiye/kawekahi
kaI
kaweke/kawekahiz/kaiye/kawekahi
kaweke/kawekahiz/kaiye/kawekahi
bIsa
bise/bIsahi/bIsahiz/bIse
bise/bIsahi/bIsahiz/bIse
ekAnabe
ekAnabeye/ekAnabee/ekAnabahi/ekAnabahiz
ekAnabeye/ekAnabee/ekAnabahi/ekAnabahiz
xonoM
xonoM/xunnUye/xunnUMye/xunnUzye/xunnahi/xunnahiz/xunnUe/xunnUMe/xunnUze
xonoM/xunnUye/xunnUMye/xunnUzye/xunnahi/xunnahiz/xunnUe/xunnUMe/xunnUze
saba
sabahiM/sabahiz
sabahiM/sabahiz
sEkadZoM
sEkadZoM/sEkadZe/sEkadZahiz/sEkadZahi
sEkadZoM/sEkadZe/sEkadZahiz/sEkadZahi
sO
sEye/sEye/sOyahiz/sOyahi/sOve
sEye/sEye/sOyahiz/sOyahi/sOve
