Adj_All_e1
amIra
amIro/amIrao/amIrahuz/amIraZWNJseho
kariyA
kariyo/kariahuz/kariAZWNJseho/karIyo/karIahuz/karIAZWNJseho
gora
goro/gorao/gorahuz/goraZWNJseho
nIlA
nIlo/nIlao/nIlahuz/nIlAZWNJseho
pIyara
pIyaro/pIaro/pIyarahuz/pIarahuz/pIrahuz/pIaraZWNJseho/pIyaraZWNJseho
asamAnI
asamaniyo/asamaniyahuz/asamAnIZWNJseho
aura
auro/aurahuz/Aoro/AuraZWNJseho
cAlU
calUo/cAlUZWNJsaBa/cAlUhuz
abuxXi
abuxXiyo/abuxXio/abuxXiyahu/abuxXiyahuM/abuxXiyahuz/abuxXiahu/abuxXiahuM/abuxXiahuz/abuxXiZWNJseho
aSawru
aSawruyo/aSawruo/aSawruyahu/aSawruyahuM/aSawruyahuz/aSawruahu/aSawruahuM/aSawruahuz/aSawruZWNJseho/asawruyo/asawruo/asawruyahu/asawruyahuM/asawruyahuz/asawruahu/asawruahuM/asawruahuz/asawruZWNJseho
aBE
aBEyo/aBEo/aBEyahu/aBEyahuM/aBEyahuz/aBEahu/aBEahuM/aBEahuz/aBEZWNJseho
jIro
jIroyo/jIroo/jIroyahu/jIroyahuM/jIroyahuz/jIroahu/jIroahuM/jIroahuz/jIroZWNJseho
javAM
javAMyo/javAMo/javAMyahu/javAMyahuM/javAMyahuz/javAMahu/javAMahuM/javAMahuz/javAMZWNJseho/javAzyo/javAzo/javAzyahu/javAzyahuM/javAzyahuz/javAzahu/javAzahuz/javAzahuM/javAzZWNJseho
BaxaIM
BaxaiMyo/BaxaiMo/BaxaiMyahu/BaxaiMyahuz/BaxaiMyahuM/BaxaiMahu/BaxaiMahuz/BaxaiMahuM/BaxaIMZWNJseho/Baxaizyo/Baxaizo/Baxaizyahu/Baxaizyahuz/BaxaizyahuM/Baxaizahu/BaxaizahuM/Baxaizahuz/BaxaIzZWNJseho
aPajUM
aPajuMyo/aPajuMo/aPajuMyahu/aPajuMyahuM/aPajuMyahuz/aPajuMahu/aPajuMahuM/aPajuMahuz/aPajUMZWNJseho/aPajuzyo/aPajuzo/aPajuzyahu/aPajuzyahuz/aPajuzyahuM/aPajuzahu/aPajuzahuz/aPajuzahuM/aPajUzZWNJseho
ekasOM
ekasOMyo/ekasOMo/ekasOMyahu/ekasOMyahuM/ekasOMyahuz/ekasOMahu/ekasOMahuM/ekasOMahuz/ekasOMZWNJseho/ekasOzyo/ekasOzo/ekasOzyahu/ekasOzyahuz/ekasOzahu/ekasOzahuM/ekasOzahuz/ekasOzZWNJseho
