Adj_f_e_vAlI
kariyakkI
karikkIye/kariyakkIye/karikiye/karIkkIye/karIyakkIye/karIkiye/karikkIyahiz/kariyakkIyahiz/karikiyahiz/karIkkIyahiz/karIyakkIyahiz/karIkiyahiz/karikkIyahi/kariyakkIyahi/karikiyahi/karIkkIyahi/karIyakkIyahi/karIkiyahi/kariyakkiye/kariyakkie/kariyakkIe
kariyaI
kariye/karIye/kariyahiz/karIyahiz/kariyahi/karIyahi
kariyaiV
kariye/karIye/kariyahiz/karIyahiz/kariyahi/karIyahi
