Adj_case_e1
aneka
anekahuz/aneko/anekaZWNJseho
anekahuz/aneko/anekaZWNJseho
kai
kaio/kEo
kaio/kEo
kaI
kaio/kEo
kaio/kEo
bIsa
bIsoM/bIso/bIsahuz/bIsao
bIsoM/bIso/bIsahuz/bIsao
ikAnabe
ekAnabeo/ekAnabeoz
ekAnabeo/ekAnabeoz
xonoM
xUnUZWNJseho/xunUZWNJseho/xunuZWNJseho/xUnuZWNJseho/xunnUZWNJseho/xUnnUZWNJseho/xunahuz
xUnUZWNJseho/xunUZWNJseho/xunuZWNJseho/xUnuZWNJseho/xunnUZWNJseho/xUnnUZWNJseho/xunahuz
saba
saBahuz/sabahuz/saBaZWNJseho/sabaZWNJseho
saBahuz/sabahuz/saBaZWNJseho/sabaZWNJseho
sEkadZoM
sEkadZo/sEkadZAZWNJseho/sEkadZahuz
sEkadZo/sEkadZAZWNJseho/sEkadZahuz
sO
sOo/saeo/sayao/saeahuz/sayaahuz
sOo/saeo/sayao/saeahuz/sayaahuz
