Adj_All_e
amIra
amIre/amIrahiz/amIrahi
kariyA
kariye/karie/karIye/karIe/kariyahiz/karIyahiz/kariyahi/karIyahi
gora
gore/gorahiz/gorahi
nIlA
nIle/nIlahi/nIlahiz
pIyara
pIare/pIyare/pIyarahiz/pIarahiz/piarahiz/piyarahiz/pIyarahi/pIarahi/piarahi/piyarahi
asamAnI
asamAniyez/asamAniez/asamAnihiz/asamAnihi
aura
Aore/Aure/aore/Aorahiz/Aurahiz/aorahiz/Aorahi/Aurahi/aorahi
cAlU
cAlUye/cAlUe/cAlUhiz/cAlUhi
abuxXi
abuxXiye/abuxXie/abuxXiyahi/abuxXiyahiM/abuxXiyahiz/abuxXiahi/abuxXiahiM/abuxXiahiz
aSawru
aSawruye/aSawrue/aSawruyahi/aSawruyahiM/aSawruyahiz/aSawruahi/aSawruahiM/aSawruahiz/asawruye/asawrue/asawruyahi/asawruyahiM/asawruyahiz/asawruahi/asawruahiM/asawruahiz
aBE
aBEye/aBEe/aBEyahi/aBEyahiM/aBEyahiz/aBEahi/aBEahiz
jIro
jIroye/jIroe/jIroyahi/jIroyahiM/jIroyahiz/jIroahi/jIroahiM
javAM
javAMye/javAMe/javAMyahi/javAMyahiz/javAMyahiM/javAMahi/javAMahiM/javAMahiz/javAzye/javAze/javAzyahi/javAzyahiM/javAzyahiz/javAzahi/javAzahiM/javAzahiz
BaxaIM
BaxaiMye/BaxaiMe/BaxaiMyahi/BaxaiMyahiM/BaxaiMyahiz/BaxaiMahi/BaxaiMahiM/BaxaiMahiz/Baxaizye/Baxaize/Baxaizyahi/BaxaizyahiM/Baxaizyahiz/Baxaizahi/BaxaizahiM/Baxaizahiz
aPajUM
aPajuMye/aPajuMe/aPajuMyahi/aPajuMyahiM/aPajuMyahiz/aPajuMahi/aPajuMahiM/aPajuMahiz/aPajuzye/aPajuze/aPajuzyahi/aPajuzyahiM/aPajuzyahiz/aPajuzahi/aPajuzahiM/aPajuzahiz
ekasOM
ekasOMye/ekasOMe/ekasOMyahi/ekasOMyahiM/ekasOMyahiz/ekasOMahi/ekasOMahiM/ekasOMahiz/ekasOzye/ekasOze/ekasOzyahi/ekasOzyahiM/ekasOzyahiz/ekasOzahi/ekasOzahiM/ekasOzahiz
