Advrb_e1
aba
abo/abau/abahuz/abahu
kala
kalho/kalho/kalo/kalho/kalhau/kalhauz/kalahu/kalahuz
Aja
Ajo/Ajuo/Ajahu/Ajahuz
parasoM
parasuo/parasovahu/parasovahuz
vihAna
vihAno/vihAnahu/vihanahu/vihanahuz
sabere
sabero/sabereyo/saberau/saberahu/saberahuz
subaha
subaho/subahaiyo/subahau/subahu/subahuz
XIre
XIraho/XIrau/XIrahu/XIrahuz
nIce
nIcaho/nIcau/nIcahu/nIcahuz
hamesA
hamesaho/hamesau/hamesahu/hamesahuz
aso
asoyo/asoeo/asoahuz/asoahuz/asoZWNJseho/asovau
begahuz
begahuzyo/begahuzo/begahuzahu/begahuzahuz/begahuzauz/begahuzZWNJseho
anaxeKe
anaxeKeyo/anaxeKayo/anaxeKeo/anaxeKao/anaxeKeahu/anaxeKehuz/anaxeKeZWNJseho
ahewu
ahewuyo/ahewuo/ahewuyahu/ahewuyahuM/ahewuyahuz/ahewuahu/ahewuahuM/ahewuahuz/ahewuZWNJseho
beAbarU
beAbaruyo/beAbaruo/beAbaruyahu/beAbaruyahuM/beAbaruyahuz/beAbaruahu/beAbaruahuz/beAbaruahuM/beAbarUZWNJseho
awi
awiyo/awio/awiyahu/awiyahuz/awiyahuM/awiahu/awiahuz/awiahuM/awiZWNJseho
kaBI
kaBiyo/kaBio/kaBiyahu/kaBiyahuz/kaBiyahuM/kaBiahu/kaBiahuz/kaBiahuM/kaBIZWNJseho
abahIM
abahiMyo/abahiMo/abahiMyahu/abahiMyahuM/abahiMahu/abahiMahuM/abahIMZWNJseho/abahizyo/abahizo/abahizyahu/abahizyahuz/abahizahu/abahizahuz/abahIzZWNJseho
abahUM
abahuMyo/abahuMo/abahuMyahu/abahuMyahuM/abahuMahu/abahuMahuM/abahUMZWNJseho/abahuzyo/abahuzo/abahuzyahu/abahuzyahuz/abahuzahu/abahuzahuz/abahUzZWNJseho
jahAM
jahAMyo/jahAMo/jahAMyahu/jahAMyahuM/jahAMahu/jahAMahuM/jahAMZWNJseho/jahAzye/jahAze/jahAzyahi/jahAzyahiz/jahAzahi/jahAzahiz
Aya
Aio/Ayio/Aiyo
