Advrb_e
aba
abai/abe/abe/abahi/abahiz
kala
kalhe/kalhie/kalai/kAlhe/kAlhai/kale/kalahi/kalahiz
Aja
Ajiye/Aje/Ajahi/Ajahiz
parasoM
parasue/parasuye/parasuvahi/parasuvahiz/parasovahi/parasovahiz
vihAna
vihAne/vihAnaye/vihAnahi/vihAnahiz
sabere
saberai/saberahi/saberahiz
subaha
subahe/subahai/subahaiz/subahiz/subahiye/subahie
XIre
XIrahi/XIrai/XIrahiz
nIce
nIcahi/nIcai/nIcahiz
hamesA
hamesahi/hamesai/hamesahiz
aso
asoye/asoe/asohi/asohiz/asohiM/asovai
begahuz
begahuzye/begahuze/begahuzahi/begahuzahiz/begahuzahiM
anaxeKe
anaxeKaye/anaxeKeye/anaxeKee/anaxeKae/anaxeKehi/anaxeKehiz/anaxeKehiM
ahewu
ahewuye/ahewue/ahewuyahi/ahewuyahiM/ahewuyahiz/ahewuahi/ahewuahiM/ahewuahiz
beAbarU
beAbaruye/beAbarue/beAbaruyahi/beAbaruyahiM/beAbaruyahiz/beAbaruahi/beAbaruahiM/beAbaruahiz
awi
awiye/awie/awiyahi/awiyahiM/awiyahiz/awiahi/awiahiM/awiahiz
kaBI
kaBiye/kaBie/kaBiyahi/kaBiyahiM/kaBiyahiz/kaBiahi/kaBiahiz/kaBiahiM/kaBai
abahIM
abahiMye/abahiMe/abahiMyahi/abahiMyahiM/abahiMahi/abahiMahiM/abahizye/abahize/abahizyahi/abahizyahiz/abahizahi/abahizahiz
abahUM
abahuMye/abahuMe/abahuMyahi/abahuMyahiM/abahuMahi/abahuMahiM/abahuzye/abahuze/abahuzyahi/abahuzyahiz/abahuzahi/abahuzahiz
jahAM
jahAMye/jahAMe/jahAMyahi/jahAMyahiM/jahAMahi/jahAMahiM/jahAzye/jahAze/jahAzyahi/jahAzyahiz/jahAzahi/jahAzahiz
Aya
Aiye/Aie
