Future
KA
KAyaba/KAeba/KEba
Kebez/KebaV/KebahI/Kayabahi/Kaebahi/Kaebahaka/Kayabahaka
KAyaba/KAiba/KEba/KAeba/Kebaya/Kebae/KebE
KAyawa/KAewa/KEwa
KAyaba/KEba/KAeba
Kebez/KebaV/KebahI/Kayabahi/Kaebahi/Kaebahaka/Kayabahaka
KAyaba/KEba/KAeba/Kebaya/Kebae/KebE
KAyawa/KAewa/KEwa
KAyaba/KEba/KAeba
Kebez/KebaV/KebahI/Kayabahi/Kaebahi/Kaebahaka/Kayabahaka
KAyaba/KAiba/KEba/KAeba/Kebaya/Kebae/KebE/KebaI
Kewi/Kewiha/Kaewiha
KAyaba/KAiba/KEba/KAeba/Kebaya/Kebae/KebE/KebaI
Kebez/KebaV/KebahI/Kayabahi/Kaebahi/Kaebahaka/Kayabahaka
KAyaba/KAiba/KEba/KAeba/Kebaya/Kebae/KebE/KebaI
Kewi/Kewiha/Kaewiha
-
-
KAyaba/KAiba/KEba/KAeba/Kebaya/Kebae/KebE/KebaI
-
-
-
KAyaba/KAiba/KEba/KAeba/Kebaya/Kebae/KebE/KebaI
-
kara
karaba
karabeM/karabaV
karaba
karawa
karaba
karabeM/karabaV
karaba
karawAha/karawA/karaWina/karaWinha
karaba
karaba/karabez
karaba
karawiha/karawi/karaWina/karaWinha
karaba
karaba/karabez
karaba
karawiha/karawi/karaWina/karaWinha
-
-
karaba
-
-
-
karaba
-
le
leba
lebaV/lebahi
leba
lewa/lewE
leba
lebaV/lebahi
leba/lebE
lewA/lewAha/leWina/leWinha
leba
lebaV/lebahi
leba
lewI/lewIha
leba
lebaV/lebahi
leba
lewI/lewIha/leWinha
-
-
leba/lebE
-
-
-
leba/lebE
-
ho
hoyaba/hoeba/hobE/hobaya/hobae
hebaV/heba/hebeM/hobe
hoyaba/hoeba/hobE/hobaya/hobae
hoyawa/hoewa/howE
hoyaba/hoeba/hobE/hobaya/hobae
hebaV/heba/hebeM/hobe
hoyaba/hoeba/hobE/hobaya/hobae
hoyawa/hoewa/howE
hoyaba/hoeba/hobE/hobaya/hobae
hebaV/heba/hebeM/hobe
hoyaba/hoeba/hobE/hobaya/hobae
hoyawa/hoewa/howE
hoyaba/hoeba/hobE/hobaya/hobae
hebaV/heba/hebeM/hobe
hoyaba/hoeba/hobE/hobaya/hobae
hewiha/heWinha/hoWina/hoWinha
-
-
hoyaba/hoeba/hobE/hobaya/hobae
-
-
-
hoyaba
-
pI
pIyaba/pIaba
piba/pibez/pibe
pIyaba/pIaba/pibE
piyawa/piawa/pIwE
pIyaba/pIaba
piba/pibez/pibe
pIyaba/pIaba/pibE
piyawa/piawa/pIwE
pIyaba/pIaba/pibE
piba/pibez/pibe
pIaba/pIyaba/pibE
piyawa/piawa/pIwE
piyaba/piaba/pIyaba/pIaba
pIaba/pIyaba/pibE
pIyaba/pIaba/pibE
piwIha/piwiha/piWina/piWinha
-
-
pIaba/pIyaba/pibE
-
-
-
pIaba/pIyaba/pibE
-
CU
CUaba/Cuaba/CUyaba/Cuyaba/CUbE/CubE
CUbaV/CubaV/CUbeM/CubeM
CUaba/Cuaba/CUyaba/Cuyaba
Cuawa/CUawa/CUwE/CuwE
CUaba/Cuaba/CUyaba/Cuyaba
CUbaV/CubaV/CUbeM/CubeM
CUaba/Cuaba/CUyaba/Cuyaba/CubE
CUwAha/CUawAha/CUawinha/CUwinha
CUaba/Cuaba/CUyaba/Cuyaba/CubE
CUbaV/CubaV/CUbeM/CubeM
CUaba/Cuaba/CUyaba/Cuyaba/CubE
CUwiha/CUawiha/CUawinha/CUwinha
CUaba/Cuaba/CUyaba/Cuyaba/CubE
CUbaV/CubaV/CUbeM/CubeM
CUaba/Cuaba/CUyaba/Cuyaba/CubE
CUwiha/CUawiha/CUawinha/CUwinha
-
-
CUaba/Cuaba/CUyaba/Cuyaba/CubE
-
-
-
CUaba/Cuaba/CUyaba/Cuyaba/CubE
-
uTa
uTaba/uTabE
uTabaV/uTabeM
uTaba/uTabE
uTawa/uTawE
uTaba/uTabE
uTaba/uTabeM
uTaba/uTabE
uTawa/uTawE
uTaba/uTabE
uTabe/uTabeM
uTaba/uTabE
uTawI/uTawIha/uTawi/uTawiha
uTaba/uTabE
uTaba/uTabeM
uTaba/uTabE
uTawI/uTawIha/uTawi/uTawiha
-
-
uTaba/uTabE
-
-
-
uTaba/uTabE
-
so
soba/sobE
sobaV/sobeM
soba/sobE
sowa/sowE
soba/sobE
sobaV/sobeM
soba/sobE
sowA/sowE
soba/sobE
sobaV/sobeM
soba/sobE
sowI/sowisowIha/sowiha/sowE
soba/sobE
sobaV/sobeM
soba/sobE
sowI/sowisowIha/sowiha/sowE
-
-
soba/sobE
-
-
-
soba/sobE
-
se
seba/sebE
sebaV/sebeM
seba/sebE
sewa/sewE
seba/sebE
sebaV/sebeM
seba/sebE
sewA/sewE
seba/sebE
sebaV/sebeM
seba/sebE
sewI/sewisewIha/sewiha/sewE
seba/sebE
sebaV/sebeM
seba/sebE
sewI/sewisewIha/sewiha/sewE
-
-
seba/sebE
-
-
-
seba/sebE
-
