Infinitive_yeke
KA
KebAka/KAikez/KAike/KenAya/KenAi/KaebAka/KEbAka/KayabAka/KAe/KAye
KebAka/KAikez/KAike/KenAya/KenAi/KaebAka/KEbAka/KayabAka/KAe/KAye
KebAka/KAikez/KAike/KenAya/KenAi/KaebAka/KEbAka/KayabAka/KAe/KAye
KebAka/KAikez/KAike/KenAya/KenAi/KaebAka/KEbAka/KayabAka/KAe/KAye
kara
karike/kaVZWNJkez/kaVZWNJke/kaeke/kayake/kaVka/kare
karike/kaVZWNJkez/kaVZWNJke/kaeke/kayake/kaVka/kare
karike/kaVZWNJkez/kaVZWNJke/kaeke/kayake/kaVka/kare
karike/kaVZWNJkez/kaVZWNJke/kaeke/kayake/kaVka/kare
le
lebAka/lEkez/lEke/lenAya/lenAi/leye/lee
lebAka/lEkez/lEke/lenAya/lenAi/leye/lee
lebAka/lEkez/lEke/lenAya/lenAi/leye/lee
lebAka/lEkez/lEke/lenAya/lenAi/leye/lee
ho
hebAka/haebAka/hayabAka/hoye/hoe
hebAka/haebAka/hayabAka/hoye/hoe
hebAka/haebAka/hayabAka/hoye/hoe
hebAka/haebAka/hayabAka/hoye/hoe
pI
pIbAka/pibAka/pIye/piye
pIbAka/pibAka/pIye/piye
pIbAka/pibAka/pIye/piye
pIbAka/pibAka/pIye/piye
CU
CUbAka/CuE/CUye/Cuye
CUbAka/CuE/CUye/Cuye
CUbAka/CuE/CUye/Cuye
CUbAka/CuE/CUye/Cuye
uTa
uTabAka/uTe
uTabAka/uTe
uTabAka/uTe
uTabAka/uTe
so
sobAka/soe/soye
sobAka/soe/soye
sobAka/soe/soye
sobAka/soe/soye
se
sebAka/seye/see
sebAka/seye/see
sebAka/seye/see
sebAka/seye/see
