Infinitive_yeke_e
KA
KevAke/Kaiye/KAye/KebAke/Kaiyeke/KaViyahiMke/KAiye
kara
karaiye/karavAke/karabAke/karaViyahiMke
uTa
uTaiye/uTavAke/uTabAke/uTaViyahiMke
ho
hovAke/hobAke/hoViyahiMke
pI
pibAke/pIvAke/piViyahiMke/pIViyahiMke
CU
CuvAke/CUvAke/CubAke/CUbAke/CuViyahiMke/CUViyahiMke
uTa
uTabAke/uTavAke/uTaViyahiMke
so
sobAke/sovAke/soViyahiMke
se
sebAke/sevAke/seViyahiMke
