kara_e1
KA
KAiyoZWNJkaV/KAyoZWNJkaV/KAiyokaV/KAiokaV
kara
kariyoZWNJkaV/kayoZWNJkaV/kariyokaV/kariokaV/kaiokaV/kaiyokaV
le
lEyoZWNJkaV/layoZWNJkaV/leiyokaV/leiokaV/laiyokaV/laiokaV
ho
hoiyoZWNJkaV/hoyoZWNJkaV/hoiyokaV/hoiokaV
pI
piyoZWNJkaV/pIyoZWNJkaV/pibiyoZWNJkaV/pibIyoZWNJkaV/pIbiyoZWNJkaV/pIbIyoZWNJkaV/pIiyokaV/piiyokaV/pIiokaV/piiokaV
CU
CuiyoZWNJkaV/CUiyoZWNJkaV/CuyoZWNJkaV/CUyoZWNJkaV/CubiyoZWNJkaV/CubIyoZWNJkaV/CUbiyoZWNJkaV/CUbIyoZWNJkaV/CUiyokaV/CUiokaV/CuiyokaV/CuiokaV
uTa
uTiyoZWNJkaV/uTiyokaV/uTiokaV/uTekaV
so
soiyoZWNJkaV/soyoZWNJkaV/soiyokaV/soiokaV
se
seiyoZWNJkaV/seyoZWNJkaV/seiyokaV/seiokaV
