kara
KA
KAkaV
kara
karikaV/karikaz/karike/kazke
le
laVZWNJkez/laVZWNJke/laVZWNJka/leke/laVkez/laVke/laVka
ho
hokaV
pI
pIbaZWNJkaV/pIZWNJkaV/pibaZWNJkaV/piZWNJkaV/pIbakaV/pIkaV/pibakaV/pikaV
CU
CUbikaV/CUkaV/CubikaV/CukaV/CUbiZWNJkaV/CUZWNJkaV/CubiZWNJkaV/CuZWNJkaV
uTa
uTiZWNJkaV/uTikaV/uTakaV
so
soVZWNJkaV/soke/sokaV
se
sebaZWNJkaV/sebakaV
