kara_e
KA
KAiyeZWNJkaV/KAyeZWNJkaV/KAiyekaV/KAiekaV
kara
kariyeZWNJkaV/kayeZWNJkaV/kariyekaV/kariekaV
le
lEyeZWNJkaV/layeZWNJkaV/leiekaV/leyikaV
ho
hoiyeZWNJkaV/hoyeZWNJkaV/hoiyekaV/hoiekaV
pI
piyeZWNJkaV/pIyeZWNJkaV/pibiyeZWNJkaV/pibIyeZWNJkaV/pIbiyeZWNJkaV/pIbIyeZWNJkaV/pIiekaV/piiyekaV/piiekaV/pIyiekaV
CU
CuiyeZWNJkaV/CUiyeZWNJkaV/CuyeZWNJkaV/CUyeZWNJkaV/CubiyeZWNJkaV/CubIyeZWNJkaV/CUbiyeZWNJkaV/CUbIyeZWNJkaV/CUiyekaV/CUiekaV/CuiekaV/CuiyekaV
uTa
uTiyeZWNJkaV/uTiyekaV/uTiekaV
so
soiyeZWNJkaV/soyEZWNJkaV/soiyekaV/soiekaV
se
seiyeZWNJkaV/seyEZWNJkaV/seiyekaV/seiekaV
