optative_ilA
KA
KAiwa/KAi/KAya/KAbE/KabECa
KAiwa/KAi/KAya/KAbE/KabECa
KAiwa/KAi/KAya/KAbE/KabECa
KAiwa/KAi/KAya/KAbE/KabECa
KAiwa/KAi/KAya/KAbE/KabECa
KAiwa/KAi/KAya/KAbE/KabECa
KAiwa/KAi/KAya/KAbE/KabECa
KAiwa/KAi/KAya/KAbE/KabECa
KAiwa/KAi/KAya/KAbE/KabECa
KAiwa/KAi/KAya/KAbE/KabECa
KAiwa/KAi/KAya/KAbE/KabECa
KAiwa/KAi/KAya/KAbE/KabECa
uTa
uTaya/uTae/uTai/uTEwa/uTE
uTaya/uTae/uTai/uTEwa/uTE
uTaya/uTae/uTai/uTEwa/uTE
uTaya/uTae/uTai/uTEwa/uTE
uTaya/uTae/uTai/uTEwa/uTE
uTaya/uTae/uTai/uTEwa/uTE
uTaya/uTae/uTai/uTEwa/uTE
uTaya/uTae/uTai/uTEwa/uTE
uTaya/uTae/uTai/uTEwa/uTE
uTaya/uTae/uTai/uTEwa/uTE
uTaya/uTae/uTai/uTEwa/uTE
uTaya/uTae/uTai/uTEwa/uTE
pI
pIbaya/pIbai/pIbae/pIbE/pIae/pIyaya
pIbaya/pIbai/pIbae/pIbE/pIae/pIyaya
pIbaya/pIbai/pIbae/pIbE/pIae/pIyaya
pIbaya/pIbai/pIbae/pIbE/pIae/pIyaya
pIbaya/pIbai/pIbae/pIbE/pIae/pIyaya
pIbaya/pIbai/pIbae/pIbE/pIae/pIyaya
pIbaya/pIbai/pIbae/pIbE/pIae/pIyaya
pIbaya/pIbai/pIbae/pIbE/pIae/pIyaya
pIbaya/pIbai/pIbae/pIbE/pIae/pIyaya
pIbaya/pIbai/pIbae/pIbE/pIae/pIyaya
pIbaya/pIbai/pIbae/pIbE/pIae/pIyaya
pIbaya/pIbai/pIbae/pIbE/pIae/pIyaya
kara
karaya/karE/karEwa/karai/karae
karaya/karE/karEwa/karai/karae
karaya/karE/karEwa/karai/karae
karaya/karE/karEwa/karai/karae
karaya/karE/karEwa/karai/karae
karaya/karE/karEwa/karai/karae
karaya/karE/karEwa/karai/karae
karaya/karE/karEwa/karai/karae
karaya/karE/karEwa/karai/karae
karaya/karE/karEwa/karai/karae
karaya/karE/karEwa/karai/karae
karaya/karE/karEwa/karai/karae
le
lEwa/lE/lai/laya/lae
lEwa/lE/lai/laya/lae
lEwa/lE/lai/laya/lae
lEwa/lE/lai/laya/lae
lEwa/lE/lai/laya/lae
lEwa/lE/lai/laya/lae
lEwa/lE/lai/laya/lae
lEwa/lE/lai/laya/lae
lEwa/lE/lai/laya/lae
lEwa/lE/lai/laya/lae
lEwa/lE/lai/laya/lae
lEwa/lE/lai/laya/lae
xe
xEwa/xE/xaya/xae/xai
xEwa/xE/xaya/xae/xai
xEwa/xE/xaya/xae/xai
xEwa/xE/xaya/xae/xai
xEwa/xE/xaya/xae/xai
xEwa/xE/xaya/xae/xai
xEwa/xE/xaya/xae/xai
xEwa/xE/xaya/xae/xai
xEwa/xE/xaya/xae/xai
xEwa/xE/xaya/xae/xai
xEwa/xE/xaya/xae/xai
xEwa/xE/xaya/xae/xai
CU
CubEwa/CubE/Cubaya/Cubae/Cubai/Cuae
CubEwa/CubE/Cubaya/Cubae/Cubai/Cuae
CubEwa/CubE/Cubaya/Cubae/Cubai/Cuae
CubEwa/CubE/Cubaya/Cubae/Cubai/Cuae
CubEwa/CubE/Cubaya/Cubae/Cubai/Cuae
CubEwa/CubE/Cubaya/Cubae/Cubai/Cuae
CubEwa/CubE/Cubaya/Cubae/Cubai/Cuae
CubEwa/CubE/Cubaya/Cubae/Cubai/Cuae
CubEwa/CubE/Cubaya/Cubae/Cubai/Cuae
CubEwa/CubE/Cubaya/Cubae/Cubai/Cuae
CubEwa/CubE/Cubaya/Cubae/Cubai/Cuae
CubEwa/CubE/Cubaya/Cubae/Cubai/Cuae
ho
hoiwa/hoi/hoyawa/hoewa/hoya/hoe/hoiCa
hoiwa/hoi/hoyawa/hoewa/hoya/hoe/hoiCa
hoiwa/hoi/hoyawa/hoewa/hoya/hoe/hoiCa
hoiwa/hoi/hoyawa/hoewa/hoya/hoe/hoiCa
hoiwa/hoi/hoyawa/hoewa/hoya/hoe/hoiCa
hoiwa/hoi/hoyawa/hoewa/hoya/hoe/hoiCa
hoiwa/hoi/hoyawa/hoewa/hoya/hoe/hoiCa
hoiwa/hoi/hoyawa/hoewa/hoya/hoe/hoiCa
hoiwa/hoi/hoyawa/hoewa/hoya/hoe/hoiCa
hoiwa/hoi/hoyawa/hoewa/hoya/hoe/hoiCa
hoiwa/hoi/hoyawa/hoewa/hoya/hoe/hoiCa
hoiwa/hoi/hoyawa/hoewa/hoya/hoe/hoiCa
so
sUwEwa/sUwaya/sUwE/sUwae/sUwai
sUwEwa/sUwaya/sUwE/sUwae/sUwai
sUwEwa/sUwaya/sUwE/sUwae/sUwai
sUwEwa/sUwaya/sUwE/sUwae/sUwai
sUwEwa/sUwaya/sUwE/sUwae/sUwai
sUwEwa/sUwaya/sUwE/sUwae/sUwai
sUwEwa/sUwaya/sUwE/sUwae/sUwai
sUwEwa/sUwaya/sUwE/sUwae/sUwai
sUwEwa/sUwaya/sUwE/sUwae/sUwai
sUwEwa/sUwaya/sUwE/sUwae/sUwai
sUwEwa/sUwaya/sUwE/sUwae/sUwai
sUwEwa/sUwaya/sUwE/sUwae/sUwai
se
sebaya/sebE/sebae/sebai/sebEwa
sebaya/sebE/sebae/sebai/sebEwa
sebaya/sebE/sebae/sebai/sebEwa
sebaya/sebE/sebae/sebai/sebEwa
sebaya/sebE/sebae/sebai/sebEwa
sebaya/sebE/sebae/sebai/sebEwa
sebaya/sebE/sebae/sebai/sebEwa
sebaya/sebE/sebae/sebai/sebEwa
sebaya/sebE/sebae/sebai/sebEwa
sebaya/sebE/sebae/sebai/sebEwa
sebaya/sebE/sebae/sebai/sebEwa
sebaya/sebE/sebae/sebai/sebEwa
