Pres_Prog_Asp_e_wa
KA
KAiwe/KAiwahi/KAiwahiz/KAewe/KAewahi/KAewahiz
pI
pIbawe/pIwe/pibawe/piwe/pibawahiz/pibawahi
uTa
uTiwe/uTawahi/uTawahiz/uTiwahiz/uTiwahi
kara
kariwe/karawahi/karawahiz/kariwahiz/kariwahi
CU
CUbiwe/Cubiwe/CUae/Cuae/Cuiwe/CUiwe/CUbiwahi/Cubiwahi/CUbiwahiz/Cubiwahiz/CUaewahiz/Cuaewahiz/CUaewahi/Cuaewahi/CUayawahiz/Cuayawahiz/CUayawahi/Cuayawahi/Cuiwahiz/Cuiwahi/CUiwahiz/CUiwahi
ho
hoiwe/hoiwahi/hoiwahiz
le
leiwe/lewahi/lewahiz
xe
xeiwe/xewahi/xewahiz
se
sebawe/sebawahi/sebawahiz
so
sobawe/sobawahi/sobawahiz
