Pres_Prtcpl_e_wa1
KA
KAiwe/KAiwahi/KAiwahiz/KAyawe
pI
pibawe/pibawahi/pibawahiz/pIbawe/pIbawahi/pIbawahiz
uTa
uiTawe/uTawe/uTawahi/uTawahiz/uTiwe/uTiwahi/uTiwahiz
kara
kariwe/kariwahi/kariwahiz
CU
Cuiwe/Cubawahi/Cubawahiz/Cubawe/CUiwe/CUbawahi/CUbawahiz/CUbawe/CUbiwahi/CUbiwahiz/Cuiwahi/Cuiwahiz/CUiwahi/CUiwahiz
ho
hoiwe/hoiwahi/hoiwahiz
le
leiwe/leiwahi/leiwahiz/lewahi/lewahiz
xe
xeiwe/xeiwahi/xeiwahiz/xewahi/xewahiz
se
sebawe/seiwe/sebawahi/sebawahiz/seiwahi/seiwahiz
so
soiwe/soiwahi/soiwahiz/sobawe/sobawahi/sobawahiz/sobiwe/sobiwahi/sobiwahiz
