PstPerf_Plus_Aux_e_yale
KA
Kenahiz/Kenahi/Kaenahiz/Kaenahi/Kayanahiz/Kayanahi/Kayale/Kayalahiz/Kayalahi/Kaele/Kaelahiz/Kaelahi/Kenaiye/Kenaiyahiz/Kenaiyahi
kara
kenahiz/kenahi/kaenahiz/kaenahi/kayanahiz/kayanahi/kayale/kayalahiz/kayalahi/Kaele/Kaelahiz/Kaelahi/kenaiye/kenaiyahiz/kenaiyahi/karane/karanahiz/karanahi
le
lenahiz/lenahi/leenahiz/leenahi/leyanahiz/leyanahi/leyale/leyalahiz/leyalahi/laele/laelahiz/laelahi/lenaiye/lenaiyahiz/lenaiyahi
xe
xenahiz/xenahi/xaenahiz/xaenahi/xayanahiz/xayanahi/xayale/xayalahiz/xayalahi/xaele/xaelahiz/xaelahi/xenaiye/xenaiyahiz/xenaiyahi
ho
hoane
CU
CUnahiz/CUnahi/Cunahiz/Cunahi/Cuyale/Cuyalahiz/Cuyalahi/CUyale/CUyalahiz/CUyalahi/CUele/CUelahiz/CUelahi/Cuele/Cuelahiz/Cuelahi/CUnaiye/CUnaiyahiz/CUnaiyahi/Cunaiye/Cunaiyahiz/Cunaiyahi/CUbanahiz/CUbanahi/Cubanahiz/Cubanahi/Cubayale/Cubayalahiz/Cubayalahi/CUbayale/CUbayalahiz/CUbayalahi/CUbaele/CUbaelahiz/CUbaelahi/Cubaele/Cubaelahiz/Cubaelahi/CUbanaiye/CUbanaiyahiz/CUbanaiyahi/Cubanaiye/Cubanaiyahiz/Cubanaiyahi/CUbinahiz/CUbinahi/Cubinahiz/Cubinahi/Cubiyale/Cubiyalahiz/Cubiyalahi/CUbiyale/CUbiyalahiz/CUbiyalahi/CUbiele/CUbielahiz/CUbielahi/Cubiele/Cubielahiz/Cubielahi/CUbinaiye/CUbinaiyahiz/CUbinaiyahi/Cubinaiye/Cubinaiyahiz/Cubinaiyahi
uTa
uTale/uTalahiz/uTalahi/uTanahi
pI
pinahiz/pine/pinahi/pInahiz/pIne/pInahi/pibanahiz/pibane/pibanahi/pIbanahiz/pIbane/pIbanahi/pibinahiz/pibine/pibinahi/pIbinahiz/pIbine/pIbinahi
se
sebane/sebine/sene/senahiz/senahi/sebanahiz/sebanahi/sebanahie/sebinahiz/sebinahi/sebinahie
so
sobane/sobine/sone/sonahiz/sonahi/sobanahiz/sobanahi/sobanahie/sobinahiz/sobinahi/sobinahie
