PstPerf_Minus_Aux_ila1
jA
gelOz/gelahuz/geliae/geliaeka
gelOz/gelahuz/geliae/geliaeka
gelez/gelahI/gaelez/gelaV/gelahaka/gelOz/gelahuz/geliae/geliaeka/geliyae/gelO
gelez/gelahI/gaelez/gelaV/gelahaka/gelOz/gelahuz/geliae/geliaeka/geliyae/gelO
gela/gelaya/gelae/gelEWa/gelaWi/gelaKina/gelaWina/gelaWuna/gelE
gela/gelaya/gelae/gelEWa/gelaWi/gelaKina/gelaWina/gelaWuna/gelE
gelOz/gelahuz/geliae/geliaeka
gelOz/gelahuz/geliae/geliaeka
gelez/gelahI/gaelez/gelaV/gelahaka/gelOz/gelahuz/geliae/geliaeka/geliyae
gelez/gelahI/gaelez/gelaV/gelahaka/gelOz/gelahuz/geliae/geliaeka/geliyae
gela/gelaya/gelae/gelEWa/gelaWi/gelaKina/gelaWina/gelaWuna
gela/gelaya/gelae/gelEWa/gelaWi/gelaKina/gelaWina/gelaWuna
