Root
KA
KA/KAbi/KAbio/KAbiyo/KAbiye/KAbie/KAie/KAiye/KAio/KAiyo
kara
kara/kari/ka/kariye/kariyo
le
le/lebi/la/lebie/lebiye/lebiyo
xe
xe/xebi/xa/xebiye/xebiyo/xebie/xebio
ho
ho/hobi/hobie/hobiye/hobio/hobiyo
pI
pI/pi/pIbi/pIbI/pibiye/pibie/pibio/pibiyo
CU
CU/Cu/CUbi/Cubi/Cubiye/Cubie/Cubio/Cubiyo
uTa
uTa/uTi/uTiye/uTie/uTio/uTiyo
so
so/sobi/sobie/sobiye/sobiyo/sobio
se
se/sebi/sebie/sebiye/sobiyo/sobio
jA
jA
