subj
KA
KAu/KaiyE/KaiE
KelaV/Kelez/Kelaha/Kaelaha/Kayalaha/KaelaV/KayalaV/Kaile
KAu/KaiO/KaiyO
Kelaka/Kaelaka/KelakaI/KelakE
KelOMha/Kelahuz/KeliE/KeliyE
Ko/KA
KaiyO/KaiO/KAu/KAU
KelA/KelAha/KaelaKinha/KayalaKinha/KaelaWinha/KaelaWina/KaelaWi
-
-
KAu/KaiO/KaiyO
-
kara
karU
kayalaha/kaelaha/kaelaV/kayalaV/kelaha/kelaV/kElaha/kElaV/kailaha/kailaV/keleM/kaelez/kailez/kayalez/kayaleM/kayale/kaile
karU/kariyO/kariO
kayalaha/kaelaha/kaelaV/kayalaV/kelaha/kelaV/kela/kElaha/kElaV/kailaha/kailaV/keleM/kaelez/kailez/kayalez/kayaleM/kayale/kaile/karI
karU/kariyO/kariO
karaV/kara
karU/kariyO/kariO
karEWa/karaiWa/karawE
-
-
karU/kariyO/kariO
-
le
liyaha/liaha/lI/liya/liyE
lelaha/lelaV/lelez
liyaha/liaha/lIM/liya/liyE/leWina/leWinha
lelaha/lelaV/lele
liyaha/liaha/lI/liya/liyE
lelaha/lelaV/lele
liyaha/liaha/lI/liya/liyE
leewa/lewa/leWina/leWinha
-
-
liyaha/liaha/lI/liya/liyE
-
ho
hoyaba/hoeba/hoya/hoe
hole/hoewe/hoiwe
hou/hoU
holE/holaya/BelE/Belaya
hoya/hobE
ho
hou/hoU
hoiWa/hoWinha/hoWina
-
-
hou/hoU
-
pI
pibU/pibI/pIbU/pIbI/piyU/piu
pIne
pibU/pIbU/pibIyE/pIbIyE/piyU/piu
pibe/pIbe/pie/piye
pibU/pibI/pIbU/pIbI/piyU/piu
piyaV/pIyaV/pI/pi/pibaV/pIbaV
pibU/pIbU/pibIyE/pIbIyE/piyU/piu
pibEwa/pIbEwa
-
-
pibU/pIbU/pibIyE/pIbIyE/piyU/piu
-
CU
CUbU/CubU/CUbI/CubI/CubE/CUbE
CuEz/Cubez
CUbU/CubU/CUbI/CubI/CUiyO/CuiyO/CUbiyO/CubiyO/CUbiO/CubiO
CulakE/Culakai/CulakaI
CuliyE/CUliyE/Culahuz/CulOz
CUbaV/CU
CUbU/CubU/CUiyO/CuiyO/CUbiyO/CubiyO/CUbiO/CubiO
CulaKinha/CulaKina
-
-
CuliyE/Culahuz/CulOz
-
uTa
uTUz/uTU/uTiyE
uTalaV/uTale/uTalez
uTUz/uTU/uTiyE
uTalE/uTalaWi
uTalahuz/uTalOz/uTalI
uTaV/uTa
uTU/uTiyO/uTiO
uTaWi/uTEwa
-
-
uTU/uTiyO/uTiO
-
so
soiyE
solez/soleM
sou/soiyO/soiO
solE/solae
soiyE/soiE
so/soaV/sovaV
sou/soiyO/soiO
sobEWa/sobaWi
-
-
sou/soiyO/soiO
-
se
sebU/sebIyE/sebiyE/sebiE
sebaV/sebeMV
sebU/sebIyE/sebiyE/sebiE
sebEWa/sebaWi
sebU/sebIyE/sebiyE/sebiE
seba/sebaV
sebIyO/sebIO
sebEWa/sebaWi
-
-
sebU/sebIyE/sebiyE/sebiE
-
